const CONFIG = { priceDa: 23900, whatsappNumber: null };
const PRODUCT = {
  id: 'robe-de-soiree-nude-strass',
  name: 'Robe de soirée nude en mousseline à strass',
  description: 'Une robe de soirée élégante en mousseline de soie rose nude, ornée de strass. Sa coupe ajustée à la taille s’évase avec grâce sur la longueur. Une étole légère complète la silhouette.',
  color: 'Nude', sizes: ['46', '48', '50'],
  images: ['/assets/robe-nude-face.jpg', '/assets/robe-nude-detail.jpg', '/assets/robe-nude-dos.jpg'],
  url: '/produit/robe-de-soiree-nude-strass/'
};
const CART_KEY = 'khadidja-cart-v1';
const BASE = location.hostname.endsWith('github.io') ? '/khadidja.github.io' : '';
const siteUrl = path => BASE + path;
const $ = (s, root = document) => root.querySelector(s);
const escapeHtml = value => String(value).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money = n => new Intl.NumberFormat('fr-DZ').format(n) + ' DA';
const price = () => Number.isFinite(CONFIG.priceDa) && CONFIG.priceDa > 0 ? money(CONFIG.priceDa) : 'Prix à confirmer';
function getCart() { try { const cart = JSON.parse(localStorage.getItem(CART_KEY)); return Array.isArray(cart) ? cart.filter(item => PRODUCT.sizes.includes(item.size) && Number.isInteger(item.quantity) && item.quantity > 0) : []; } catch { return []; } }
function saveCart(cart) { localStorage.setItem(CART_KEY, JSON.stringify(cart)); updateCount(); }
function count() { return getCart().reduce((sum, item) => sum + item.quantity, 0); }
function updateCount() { document.querySelectorAll('[data-cart-count]').forEach(el => el.textContent = count()); }
const icon = name => ({search:'<circle cx="11" cy="11" r="7"/><path d="m16 16 5 5"/>',bag:'<path d="M4 8h16l-1 13H5L4 8Z"/><path d="M9 9V6a3 3 0 0 1 6 0v3"/>',user:'<circle cx="12" cy="7" r="4"/><path d="M4 21a8 8 0 0 1 16 0"/>',menu:'<path d="M3 6h18M3 12h18M3 18h18"/>',close:'<path d="M5 5l14 14M19 5 5 19"/>',heart:'<path d="M20.8 4.6a5.5 5.5 0 0 0-7.8 0L12 5.7l-1.1-1.1a5.5 5.5 0 0 0-7.8 7.8L12 21l8.8-8.6a5.5 5.5 0 0 0 0-7.8Z"/>',arrow:'<path d="M4 12h16m-6-6 6 6-6 6"/>',truck:'<path d="M2 6h12v11H2zM14 9h4l4 4v4h-8z"/><circle cx="6" cy="19" r="2"/><circle cx="18" cy="19" r="2"/>',check:'<path d="m4 12 5 5L20 6"/>'}[name] || '');
const svg = name => `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${icon(name)}</svg>`;
function header() { return `<div class="top-promo">UNE ALLURE D’EXCEPTION POUR CHAQUE OCCASION</div><header class="site-header"><div class="header-inner"><button class="icon-button mobile-menu" id="menu-toggle" aria-label="Ouvrir le menu">${svg('menu')}</button><a class="brand" href="/" aria-label="Khadidja Boutique, accueil"><img src="/assets/logo-transparent.png" alt="Khadidja Boutique"></a><div class="header-actions"><button class="icon-button search-toggle" id="search-toggle" aria-label="Rechercher">${svg('search')}</button><a class="icon-button bag-link" href="/panier/" aria-label="Panier">${svg('bag')}<span class="bag-count" data-cart-count>0</span></a></div></div><nav class="main-nav" id="main-nav" aria-label="Navigation principale"><a href="/">ACCUEIL</a><a href="/#collection">ROBES DE SOIRÉE</a><a href="/produit/robe-de-soiree-nude-strass/">NOUVEAUTÉS</a><a href="/#maison">LA MAISON</a></nav><form class="search-panel" id="search-form" role="search" hidden><label for="search-input">Rechercher une robe</label><div><input id="search-input" type="search" placeholder="Robe de soirée, strass, nude…"><button type="submit">RECHERCHER</button></div></form></header>`; }
function footer() { return `<footer class="footer" id="maison"><div class="footer-grid"><div><img class="footer-logo" src="/assets/logo-transparent.png" alt=""><p>Des robes pour célébrer chaque moment qui compte.</p></div><div><h3>EXPLORER</h3><a href="/">Accueil</a><a href="/#collection">Robes de soirée</a><a href="/panier/">Mon panier</a></div><div><h3>INFORMATIONS</h3><p>Tailles disponibles : 46, 48, 50</p><p>Livraison à confirmer auprès de la boutique.</p></div><div><h3>KHADIDJA BOUTIQUE</h3><p>Élégance et féminité pour vos plus belles occasions.</p></div></div><div class="footer-bottom">© ${new Date().getFullYear()} Khadidja Boutique</div></footer>`; }
function card() { return `<article class="product-card"><a href="${PRODUCT.url}" class="card-image"><img src="${PRODUCT.images[0]}" alt="${PRODUCT.name}" loading="lazy"><span class="new-tag">NOUVEAUTÉ</span></a><div class="card-details"><div class="small-label">KHADIDJA BOUTIQUE</div><a class="card-name" href="${PRODUCT.url}">${PRODUCT.name}</a><div class="card-price">${price()}</div><div class="color-label"><span class="color-dot"></span> Nude</div></div></article>`; }
function home() { return `<main><section class="hero"><div class="hero-photo"><img src="${PRODUCT.images[0]}" alt="Robe de soirée nude portée en extérieur"></div><div class="hero-copy"><div class="eyebrow">LA COLLECTION SOIRÉE</div><h1>L’élégance pour<br>vos plus beaux moments</h1><p>Des silhouettes féminines et des détails précieux, pensés pour vous accompagner lors de chaque occasion.</p><a class="button button-dark" href="#collection">DÉCOUVRIR LA COLLECTION ${svg('arrow')}</a></div></section><section class="selling-points"><div>${svg('truck')} <span>Livraison à confirmer</span></div><div>${svg('heart')} <span>Une sélection pensée pour vous</span></div><div>${svg('check')} <span>Tailles 46 à 50</span></div></section><section class="collection section-wrap" id="collection"><div class="section-heading"><div><span class="eyebrow">DÉCOUVRIR</span><h2>Nos robes de soirée</h2></div><span class="result-count">1 ARTICLE</span></div><div class="collection-layout"><aside class="filters"><h3>CATÉGORIES</h3><a class="filter-active" href="#collection">Robes de soirée <span>1</span></a><hr><h3>TAILLES</h3><div class="filter-sizes"><span>46</span><span>48</span><span>50</span></div><hr><h3>COULEUR</h3><p><span class="color-dot"></span> Nude</p></aside><div class="product-list"><div class="sort-row"><span>La sélection Khadidja</span><span>1 résultat</span></div><div class="product-grid">${card()}</div></div></div></section><section class="editorial"><div class="editorial-image"><img src="${PRODUCT.images[2]}" alt="Vue de dos de la robe de soirée nude" loading="lazy"></div><div class="editorial-text"><span class="eyebrow">L’ART DE BRILLER</span><h2>Une robe,<br>un moment inoubliable</h2><p>La légèreté de la mousseline rencontre l’éclat discret des strass pour une allure naturellement remarquable.</p><a href="${PRODUCT.url}" class="text-link">VOIR LA ROBE ${svg('arrow')}</a></div></section></main>`; }
function product() { return `<main class="product-main section-wrap"><div class="breadcrumbs"><a href="/">Accueil</a><span>/</span><a href="/#collection">Robes de soirée</a><span>/</span><span>Robe nude à strass</span></div><div class="product-layout"><div class="gallery"><div class="thumbs">${PRODUCT.images.map((src,i)=>`<button class="thumb ${i===0?'active':''}" data-image="${i}" aria-label="Voir l’image ${i+1}"><img src="${src}" alt=""></button>`).join('')}</div><div class="main-image"><img id="main-product-image" src="${PRODUCT.images[0]}" alt="${PRODUCT.name}"></div></div><div class="product-info"><div class="eyebrow">KHADIDJA BOUTIQUE · ROBES DE SOIRÉE</div><h1>${PRODUCT.name}</h1><div class="sku">Réf. KH-001</div><div class="product-price">${price()}</div><div class="rule"></div><p class="product-description">${PRODUCT.description}</p><div class="field-title">COULEUR : <strong>NUDE</strong></div><div class="swatch" aria-label="Nude sélectionné"><span></span></div><div class="field-title size-title">TAILLE : <strong id="selected-size">Sélectionnez une taille</strong></div><div class="size-options">${PRODUCT.sizes.map(size=>`<button type="button" data-size="${size}" aria-pressed="false">${size}</button>`).join('')}</div><p class="field-error" id="size-error" role="alert"></p><div class="quantity-wrap"><span class="field-title">QUANTITÉ</span><div class="qty-control"><button type="button" data-qty="minus" aria-label="Diminuer la quantité">−</button><span id="product-qty">1</span><button type="button" data-qty="plus" aria-label="Augmenter la quantité">+</button></div></div><button class="button button-dark add-cart" id="add-cart">AJOUTER AU PANIER ${svg('bag')}</button><p class="product-note">La disponibilité et les modalités de livraison seront confirmées par la boutique.</p><div class="detail-accordion"><details open><summary>DESCRIPTION</summary><p>${PRODUCT.description}</p></details><details><summary>DÉTAILS</summary><p>Couleur : nude. Matière décrite : mousseline de soie. Ornement : strass. Tailles : 46, 48 et 50.</p></details></div></div></div><section class="more-section"><div class="section-heading"><div><span class="eyebrow">À DÉCOUVRIR</span><h2>Dans la collection</h2></div></div>${card()}</section></main>`; }
function cart() { const items=getCart(); if(!items.length) return `<main class="simple-page section-wrap"><h1>Mon panier</h1><div class="empty-state">${svg('bag')}<h2>Votre panier est vide</h2><p>Découvrez notre première robe de soirée.</p><a class="button button-dark" href="/#collection">DÉCOUVRIR LA COLLECTION</a></div></main>`; return `<main class="simple-page section-wrap"><h1>Mon panier <span>(${count()})</span></h1><div class="cart-layout"><div class="cart-items">${items.map(item=>`<article class="cart-item" data-size="${item.size}"><a href="${PRODUCT.url}"><img src="${PRODUCT.images[0]}" alt="${PRODUCT.name}"></a><div><a class="cart-item-name" href="${PRODUCT.url}">${PRODUCT.name}</a><p>Couleur : Nude<br>Taille : ${item.size}</p><strong>${price()}</strong><div class="cart-item-actions"><div class="qty-control"><button data-cart-change="minus" data-size="${item.size}" aria-label="Diminuer la quantité">−</button><span>${item.quantity}</span><button data-cart-change="plus" data-size="${item.size}" aria-label="Augmenter la quantité">+</button></div><button class="remove-link" data-cart-remove="${item.size}">Supprimer</button></div></div></article>`).join('')}</div><aside class="summary"><h2>RÉCAPITULATIF</h2><div><span>Articles (${count()})</span><strong>${CONFIG.priceDa ? money(items.reduce((sum,item)=>sum+item.quantity*CONFIG.priceDa,0)) : 'À confirmer'}</strong></div><div><span>Livraison</span><strong>À confirmer</strong></div><hr><div class="total"><span>Total estimé</span><strong>${CONFIG.priceDa ? money(items.reduce((sum,item)=>sum+item.quantity*CONFIG.priceDa,0)) : 'À confirmer'}</strong></div><a class="button button-dark" href="/commande/">PASSER COMMANDE ${svg('arrow')}</a><a class="continue-link" href="/#collection">Continuer mes achats</a></aside></div></main>`; }
function checkout() { const items=getCart(); if(!items.length) return `<main class="simple-page section-wrap"><h1>Ma commande</h1><div class="empty-state"><h2>Votre panier est vide</h2><a class="button button-dark" href="/#collection">VOIR LES ROBES</a></div></main>`; return `<main class="simple-page section-wrap"><div class="breadcrumbs"><a href="/panier/">Panier</a><span>/</span>Commande</div><h1>Finaliser ma commande</h1><div class="cart-layout"><form id="checkout-form" class="checkout-form"><h2>VOS COORDONNÉES</h2><p>Renseignez vos informations pour préparer votre demande.</p><div class="form-grid"><label>Nom et prénom *<input name="name" autocomplete="name" required maxlength="100"></label><label>Téléphone *<input name="phone" type="tel" autocomplete="tel" required maxlength="30"></label><label>Wilaya *<input name="wilaya" autocomplete="address-level1" required maxlength="80"></label><label>Commune *<input name="commune" autocomplete="address-level2" required maxlength="80"></label></div><label>Adresse de livraison *<input name="address" autocomplete="street-address" required maxlength="200"></label><label>Précisions pour la commande<textarea name="notes" rows="4" maxlength="500" placeholder="Informations utiles pour la livraison…"></textarea></label><p class="checkout-warning">Les frais de livraison doivent être confirmés avant validation définitive.</p><button class="button button-dark" type="submit">${CONFIG.whatsappNumber ? 'ENVOYER LA DEMANDE SUR WHATSAPP' : 'PRÉPARER MA DEMANDE'} ${svg('arrow')}</button><div id="checkout-result" class="checkout-result" hidden></div></form><aside class="summary"><h2>VOTRE COMMANDE</h2>${items.map(item=>`<div class="checkout-item"><img src="${PRODUCT.images[0]}" alt=""><p>${PRODUCT.name}<small>Nude · Taille ${item.size} · Qté ${item.quantity}</small></p></div>`).join('')}<hr><div><span>Articles</span><strong>${count()}</strong></div><div><span>Prix</span><strong>${CONFIG.priceDa ? money(items.reduce((sum,item)=>sum+item.quantity*CONFIG.priceDa,0)) : 'À confirmer'}</strong></div><div><span>Livraison</span><strong>À confirmer</strong></div></aside></div></main>`; }
function setup() { const page=document.body.dataset.page; const markup=header()+(page==='product'?product():page==='cart'?cart():page==='checkout'?checkout():page==='collection'?collectionPage():page==='new'?newPage():page==='guide'?guidePage():page==='about'?aboutPage():page==='help'?helpPage():home())+footer(); $('#app').innerHTML=markup.replace(/(href|src)="\//g, `$1="${BASE}/`); updateCount(); $('#menu-toggle').addEventListener('click',()=>$('#main-nav').classList.toggle('open')); $('#search-toggle').addEventListener('click',()=>{ const panel=$('#search-form'); panel.hidden=!panel.hidden; if(!panel.hidden) $('#search-input').focus(); }); $('#search-form').addEventListener('submit',e=>{e.preventDefault(); location.href=siteUrl('/#collection');}); if(page==='product') setupProduct(); if(page==='cart') setupCart(); if(page==='checkout') setupCheckout(); if(typeof setupExtras==='function') setupExtras(); }
function setupProduct() { let selectedSize=null, qty=1; document.querySelectorAll('[data-image]').forEach(button=>button.addEventListener('click',()=>{ document.querySelectorAll('.thumb').forEach(el=>el.classList.remove('active')); button.classList.add('active'); const i=Number(button.dataset.image); $('#main-product-image').src=siteUrl(PRODUCT.images[i]); $('#main-product-image').alt=`${PRODUCT.name}, vue ${i+1}`; })); document.querySelectorAll('[data-size]').forEach(button=>button.addEventListener('click',()=>{ selectedSize=button.dataset.size; document.querySelectorAll('[data-size]').forEach(el=>el.setAttribute('aria-pressed',String(el===button))); $('#selected-size').textContent=selectedSize; $('#size-error').textContent=''; })); document.querySelectorAll('[data-qty]').forEach(button=>button.addEventListener('click',()=>{qty=Math.max(1,Math.min(99,qty+(button.dataset.qty==='plus'?1:-1))); $('#product-qty').textContent=qty;})); $('#add-cart').addEventListener('click',()=>{if(!selectedSize){$('#size-error').textContent='Veuillez choisir une taille.';return;} const cart=getCart(), existing=cart.find(item=>item.size===selectedSize); if(existing) existing.quantity=Math.min(99,existing.quantity+qty); else cart.push({size:selectedSize,quantity:qty}); saveCart(cart); location.href=siteUrl('/panier/');}); }
function setupCart() { document.querySelectorAll('[data-cart-change]').forEach(button=>button.addEventListener('click',()=>{let cart=getCart();const item=cart.find(el=>el.size===button.dataset.size);if(item)item.quantity+=button.dataset.cartChange==='plus'?1:-1;cart=cart.filter(el=>el.quantity>0);saveCart(cart);setup();})); document.querySelectorAll('[data-cart-remove]').forEach(button=>button.addEventListener('click',()=>{saveCart(getCart().filter(el=>el.size!==button.dataset.cartRemove));setup();})); }
function setupCheckout() { const form=$('#checkout-form'); if(!form)return; form.addEventListener('submit',async e=>{e.preventDefault(); const data=new FormData(form), items=getCart(); const fields=['name','phone','wilaya','commune','address','notes']; const values=Object.fromEntries(fields.map(key=>[key,String(data.get(key)||'').trim()])); const lines=[`Bonjour Khadidja Boutique, je souhaite commander :`,...items.map(item=>`• ${PRODUCT.name} — Nude, taille ${item.size}, quantité ${item.quantity}`),`Prix : ${CONFIG.priceDa ? money(items.reduce((sum,item)=>sum+item.quantity*CONFIG.priceDa,0)) : 'à confirmer'}`,`Nom : ${values.name}`,`Téléphone : ${values.phone}`,`Wilaya : ${values.wilaya}`,`Commune : ${values.commune}`,`Adresse : ${values.address}`,`Précisions : ${values.notes||'Aucune'}`];const message=lines.join('\n'); if(CONFIG.whatsappNumber){window.open(`https://wa.me/${CONFIG.whatsappNumber}?text=${encodeURIComponent(message)}`,'_blank','noopener');return;} const result=$('#checkout-result');result.hidden=false;result.innerHTML=`<strong>Votre demande est prête.</strong><p>Copiez ce récapitulatif et transmettez-le à la boutique. Aucun message n’a encore été envoyé.</p><textarea readonly rows="12" id="order-message">${escapeHtml(message)}</textarea><button type="button" class="button button-outline" id="copy-order">COPIER LA DEMANDE</button>`;$('#copy-order').addEventListener('click',async()=>{await navigator.clipboard.writeText(message);$('#copy-order').textContent='DEMANDE COPIÉE';});result.scrollIntoView({behavior:'smooth',block:'center'}); }); }
document.addEventListener('DOMContentLoaded',setup);

