// Legal information and consent. No optional trackers are installed on this site.
const LEGAL_LABELS = {
  information: ['INFORMATIONS & POLITIQUES', 'INFORMATION & POLICIES', 'المعلومات والسياسات'],
  privacy: ['Confidentialité', 'Privacy policy', 'سياسة الخصوصية'],
  cookies: ['Politique de cookies', 'Cookie policy', 'سياسة ملفات تعريف الارتباط'],
  terms: ['Conditions générales de vente', 'Terms of sale', 'شروط البيع'],
  delivery: ['Livraison & retours', 'Delivery & returns', 'التوصيل والإرجاع'],
  notices: ['Informations légales', 'Legal information', 'المعلومات القانونية'],
  use: ['Conditions d’utilisation', 'Terms of use', 'شروط الاستخدام'],
  settings: ['Gérer mes cookies', 'Manage cookies', 'إدارة ملفات تعريف الارتباط'],
  updated: ['Mis à jour le 29/09/2026', 'Updated on 29/09/2026', 'آخر تحديث: 29/09/2026'],
  intro: ['Des informations claires pour acheter en toute confiance.', 'Clear information to help you shop with confidence.', 'معلومات واضحة لتتسوقي بثقة.'],
  question: ['Une question concernant ces informations ?', 'Questions about this information?', 'هل لديك سؤال حول هذه المعلومات؟'],
  contact: ['CONTACTER LA BOUTIQUE', 'CONTACT THE STORE', 'تواصلي مع المتجر'],
  bannerTitle: ['Votre confidentialité compte', 'Your privacy matters', 'خصوصيتك مهمة'],
  bannerText: ['Nous utilisons des stockages nécessaires au panier, à la connexion et aux réglages que vous choisissez. Aucun traceur publicitaire ni de mesure d’audience n’est actuellement utilisé.', 'We use storage needed for your cart, sign-in and the settings you choose. No advertising or audience measurement trackers are currently used.', 'نستخدم التخزين اللازم للسلة وتسجيل الدخول والإعدادات التي تختارينها. لا نستخدم حالياً أدوات تتبع إعلانية أو لقياس الزيارات.'],
  accept: ['Tout accepter', 'Accept all', 'قبول الكل'],
  reject: ['Refuser les optionnels', 'Reject optional', 'رفض الاختيارية'],
  customize: ['Personnaliser', 'Customize', 'تخصيص'],
  save: ['ENREGISTRER MES CHOIX', 'SAVE MY CHOICES', 'حفظ اختياراتي'],
  close: ['Fermer', 'Close', 'إغلاق'],
  settingsTitle: ['Vos préférences de cookies', 'Your cookie preferences', 'تفضيلات ملفات تعريف الارتباط'],
  settingsText: ['Les technologies nécessaires restent actives. Les catégories optionnelles ci-dessous ne sont pas utilisées : aucun outil ne sera chargé à votre insu. Vous pouvez revenir ici à tout moment.', 'Necessary technologies stay active. The optional categories below are not in use: no tools will be loaded without your knowledge. You can return here at any time.', 'تبقى التقنيات الضرورية مفعّلة. الفئات الاختيارية أدناه غير مستخدمة، ولا تُحمّل أي أدوات دون علمك. يمكنك العودة إلى هنا في أي وقت.'],
  necessary: ['Nécessaires & réglages demandés', 'Necessary & requested settings', 'الضرورية والإعدادات المطلوبة'],
  necessaryText: ['Panier, sécurité, session de connexion, langue, devise et mémorisation de votre choix de confidentialité.', 'Cart, security, sign-in session, language, currency and your privacy choice.', 'السلة والأمان وجلسة تسجيل الدخول واللغة والعملة وحفظ اختيار الخصوصية.'],
  analytics: ['Mesure d’audience', 'Audience measurement', 'قياس الزيارات'],
  analyticsText: ['Aucun outil de statistiques de navigation installé.', 'No browsing analytics tools are installed.', 'لا توجد أدوات مثبتة لتحليل التصفح.'],
  ads: ['Publicité & personnalisation marketing', 'Advertising & marketing personalization', 'الإعلانات والتخصيص التسويقي'],
  adsText: ['Aucun pixel publicitaire ni suivi marketing installé.', 'No advertising pixels or marketing trackers are installed.', 'لا توجد وحدات تتبع إعلانية أو تسويقية مثبتة.'],
  active: ['Toujours actifs', 'Always active', 'مفعّلة دائماً'],
  unused: ['Non utilisés', 'Not in use', 'غير مستخدمة'],
  saved: ['Vos préférences ont été enregistrées.', 'Your preferences have been saved.', 'تم حفظ تفضيلاتك.']
};
const LEGAL_ROUTES = {privacy:'/confidentialite/', cookies:'/cookies/', terms:'/conditions-generales-vente/', delivery:'/livraison-retours/', notices:'/mentions-legales/', use:'/conditions-utilisation/'};
function legalLangIndex() { return {fr:0,en:1,ar:2}[currentLanguage()] ?? 0; }
function legalText(key) { return LEGAL_LABELS[key][legalLangIndex()]; }
const LEGAL_DOCUMENTS = {
  privacy: [
    [['Les données que nous utilisons','The data we use','البيانات التي نستخدمها'], ['Pour traiter une commande, nous recueillons votre nom, votre téléphone, la wilaya, la commune, l’adresse ou les informations de retrait, les articles choisis et les notes que vous nous transmettez. La commande en dinars ne demande pas d’adresse e-mail. Un compte de connexion utilise une adresse e-mail et une authentification gérée par Firebase. Évitez d’inscrire des données sensibles dans les notes.', 'To process an order, we collect your name, phone number, wilaya, commune, delivery or pickup details, selected items and any notes you provide. Dinar checkout does not ask for an email address. Sign-in accounts use an email address and Firebase authentication. Please avoid entering sensitive information in order notes.', 'لمعالجة الطلب، نجمع الاسم ورقم الهاتف والولاية والبلدية والعنوان أو بيانات الاستلام والمنتجات المختارة والملاحظات التي ترسلينها. الطلب بالدينار لا يتطلب بريداً إلكترونياً. تستخدم حسابات تسجيل الدخول بريداً إلكترونياً ومصادقة Firebase. تجنبي إدخال بيانات حساسة في الملاحظات.']],
    [['Pourquoi ces données sont nécessaires','Why we need this data','لماذا نحتاج هذه البيانات'], ['Ces informations permettent de préparer et suivre votre commande, vous contacter à son sujet, organiser la livraison et assurer le service après-vente. Les réglages de langue et de devise servent à afficher le site selon vos choix. Le traitement repose sur la préparation ou l’exécution de votre achat, la sécurité du service et, lorsque cela s’applique, nos obligations légales. Aucun abonnement marketing automatique n’est créé lors d’une commande.', 'This information helps us prepare and track your order, contact you about it, arrange delivery and provide after-sales support. Language and currency settings display the site according to your choices. Processing is based on preparing or fulfilling your purchase, service security and applicable legal duties. Placing an order does not automatically subscribe you to marketing.', 'تتيح هذه المعلومات تجهيز الطلب ومتابعته والتواصل معك بشأنه وترتيب التوصيل وخدمة ما بعد البيع. تُستخدم إعدادات اللغة والعملة لعرض الموقع وفق اختياراتك. تستند المعالجة إلى التحضير للشراء أو تنفيذه وأمان الخدمة والالتزامات القانونية المطبقة. لا يؤدي الطلب إلى اشتراك تسويقي تلقائي.']],
    [['Qui peut accéder aux informations','Who can access information','من يمكنه الوصول إلى المعلومات'], ['L’équipe habilitée de Khadidja Boutique accède aux commandes pour les gérer. Google Firebase héberge les données et gère les connexions ; la base Firestore est située dans la région de Madrid. Pour une expédition, les coordonnées et les informations du colis nécessaires sont transmises à Yalidine au moyen d’un relais Google Apps Script. Le site est hébergé sur GitHub Pages. Ces prestataires peuvent traiter des données techniques dans différents pays selon leurs propres conditions. Nous ne vendons pas vos données personnelles.', 'Authorized Khadidja Boutique staff access orders to manage them. Google Firebase hosts data and manages sign-in; the Firestore database is in the Madrid region. Delivery contact and parcel details needed for shipment are sent to Yalidine through a Google Apps Script relay. GitHub Pages hosts the website. These providers may process technical data in different countries under their own terms. We do not sell your personal data.', 'يصل فريق خديجة المخوّل إلى الطلبات لإدارتها. تستضيف Google Firebase البيانات وتدير تسجيل الدخول، وتقع قاعدة Firestore في منطقة مدريد. تُرسل بيانات الاتصال والتوصيل الضرورية إلى ياليدين عبر وسيط Google Apps Script. يُستضاف الموقع على GitHub Pages. قد تعالج هذه الجهات بيانات تقنية في دول مختلفة وفق شروطها. لا نبيع بياناتك الشخصية.']],
    [['Conservation et sécurité','Retention and security','الاحتفاظ والأمان'], ['Les données de commande sont conservées pour le suivi, le service après-vente et les obligations légales applicables. Leur durée dépend de ces finalités ; une demande de suppression peut être examinée sans effacer les éléments dont la conservation reste obligatoire. L’accès à l’administration est protégé par authentification et par des droits d’accès. Le panier et vos réglages restent dans votre navigateur jusqu’à leur suppression ou leur modification. Le choix de cookies expire après 6 mois.', 'Order data is retained for fulfilment, after-sales support and applicable legal duties. Retention depends on these purposes; deletion requests can be reviewed while keeping records that must legally be retained. Administration access is protected by authentication and access permissions. Your cart and settings stay in your browser until cleared or changed. Cookie choices expire after 6 months.', 'تُحفظ بيانات الطلب للمتابعة وخدمة ما بعد البيع والالتزامات القانونية المطبقة. تتوقف مدة الاحتفاظ على هذه الأغراض؛ تُدرس طلبات الحذف مع الاحتفاظ بما يلزم قانوناً. تحمي المصادقة وصلاحيات الوصول لوحة الإدارة. تبقى السلة والإعدادات في متصفحك حتى حذفها أو تعديلها. ينتهي اختيار ملفات تعريف الارتباط بعد 6 أشهر.']],
    [['Vos droits et votre contact','Your rights and contact','حقوقك والتواصل'], ['Vous pouvez nous demander l’accès à vos données, leur correction ou leur suppression, et poser toute question sur leur utilisation. Les demandes sont traitées dans les limites de la législation applicable et peuvent nécessiter une vérification de votre identité. Écrivez à youcefkhaldi11@hotmail.com en indiquant la référence de commande si votre demande concerne un achat. Selon votre situation, vous pouvez également saisir l’autorité compétente en matière de protection des données.', 'You can request access to your data, correction or deletion, and ask questions about its use. Requests are handled under applicable law and may require identity verification. Email youcefkhaldi11@hotmail.com with the order reference if your request relates to a purchase. Depending on your circumstances, you may also contact the competent data protection authority.', 'يمكنك طلب الوصول إلى بياناتك أو تصحيحها أو حذفها والاستفسار عن استخدامها. تُعالج الطلبات وفق القانون المطبق وقد تتطلب التحقق من الهوية. راسلينا على youcefkhaldi11@hotmail.com مع مرجع الطلب إذا تعلق الأمر بشراء. يمكنك أيضاً الرجوع إلى جهة حماية البيانات المختصة حسب حالتك.']]
  ],
  cookies: [
    [['Cookies et stockage local','Cookies and local storage','ملفات تعريف الارتباط والتخزين المحلي'], ['Un cookie est un petit fichier enregistré par un navigateur. Le site utilise aussi le stockage local et les mécanismes de stockage de Firebase : ces technologies remplissent des fonctions similaires et sont couvertes par cette politique.', 'A cookie is a small file saved by a browser. This site also uses local storage and Firebase storage mechanisms: these technologies serve similar functions and are covered by this policy.', 'ملف تعريف الارتباط ملف صغير يحفظه المتصفح. يستخدم الموقع أيضاً التخزين المحلي وآليات التخزين الخاصة بـ Firebase، وهي تقنيات تؤدي وظائف مشابهة وتشملها هذه السياسة.']],
    [['Ce que le site enregistre','What the website stores','ما الذي يحفظه الموقع'], ['Le panier est mémorisé sous khadidja-cart-v2. La langue et la devise choisies sont conservées sous khadidja-language et khadidja-currency. Firebase peut conserver une session d’authentification pour les espaces connectés. Votre réponse au bandeau est enregistrée sous khadidja-cookie-consent-v1 pour 6 mois. Ces informations ne servent pas à vous suivre à des fins publicitaires.', 'The cart is saved under khadidja-cart-v2. Your language and currency choices are stored under khadidja-language and khadidja-currency. Firebase may retain an authentication session for signed-in areas. Your banner choice is saved under khadidja-cookie-consent-v1 for 6 months. This information is not used to track you for advertising.', 'تُحفظ السلة تحت khadidja-cart-v2، واللغة والعملة تحت khadidja-language وkhadidja-currency. قد تحفظ Firebase جلسة المصادقة للمساحات المتصلة. يُحفظ جوابك على الشريط تحت khadidja-cookie-consent-v1 لمدة 6 أشهر. لا تُستخدم هذه المعلومات لتتبعك لأغراض إعلانية.']],
    [['Technologies optionnelles','Optional technologies','التقنيات الاختيارية'], ['Aucun outil de mesure d’audience, pixel publicitaire ou traceur marketing n’est actuellement installé. Les catégories correspondantes sont donc indiquées comme non utilisées dans le panneau de préférences. Accepter le bandeau n’active aucun service publicitaire. Si de tels services sont ajoutés, une nouvelle version du consentement devra être demandée avant leur activation.', 'No audience measurement tools, advertising pixels or marketing trackers are currently installed. These categories are therefore marked as not in use in the preferences panel. Accepting the banner does not activate advertising services. If such services are added, a new consent version must be requested before they are enabled.', 'لا توجد حالياً أدوات لقياس الزيارات أو وحدات تتبع إعلانية أو تسويقية. تظهر هذه الفئات على أنها غير مستخدمة في لوحة التفضيلات. قبول الشريط لا يفعّل خدمات إعلانية. إذا أُضيفت هذه الخدمات، يجب طلب موافقة جديدة قبل تفعيلها.']],
    [['Modifier ou effacer vos choix','Change or clear your choices','تعديل اختياراتك أو حذفها'], ['Le lien « Gérer mes cookies » est disponible au bas de chaque page. Le refus des technologies optionnelles ne bloque pas l’achat. Vous pouvez également effacer les données du site dans votre navigateur ; cela peut supprimer le panier et vous déconnecter. Les réglages et le panier n’ont pas de date d’expiration automatique. Les technologies strictement nécessaires ne sont pas désactivées depuis le panneau.', 'The “Manage cookies” link is available at the bottom of every page. Rejecting optional technologies does not prevent shopping. You can also clear site data in your browser; this may clear your cart and sign you out. Settings and cart storage do not expire automatically. Strictly necessary technologies cannot be disabled in the panel.', 'يتوفر رابط «إدارة ملفات تعريف الارتباط» أسفل كل صفحة. رفض التقنيات الاختيارية لا يمنع الشراء. يمكنك أيضاً مسح بيانات الموقع في المتصفح؛ وقد يؤدي ذلك إلى حذف السلة وتسجيل الخروج. لا تنتهي صلاحية السلة والإعدادات تلقائياً. لا يمكن تعطيل التقنيات الضرورية من اللوحة.']]
  ],
  terms: [
    [['Produits et disponibilité','Products and availability','المنتجات والتوفر'], ['Khadidja Boutique propose des robes pour femme. Chaque fiche présente les photos, le prix, les couleurs et les tailles disponibles. L’affichage des couleurs peut varier selon l’écran. Consultez le guide des tailles et contactez-nous en cas de doute. La disponibilité d’un article reste soumise au stock au moment du traitement de la commande.', 'Khadidja Boutique sells women’s dresses. Each product page shows photos, price, available colours and sizes. Colours may vary depending on your screen. Check the size guide and contact us if unsure. Availability depends on stock when the order is processed.', 'تبيع خديجة بوتيك فساتين نسائية. تعرض صفحة كل منتج الصور والسعر والألوان والمقاسات المتاحة. قد يختلف عرض اللون حسب الشاشة. راجعي دليل المقاسات وتواصلي معنا عند الشك. يخضع توفر المنتج للمخزون عند معالجة الطلب.']],
    [['Prix et devises','Prices and currencies','الأسعار والعملات'], ['Les prix de référence sont en dinars algériens. L’affichage en euros et en dollars utilise les taux fixés par la boutique : 1 EUR = 280 DA et 1 USD = 250 DA. Ces taux sont des taux d’affichage, pas une cotation bancaire. Les frais de livraison sont ajoutés séparément et le total est affiché avant la validation. Toute condition supplémentaire doit être annoncée avant confirmation de votre achat.', 'Reference prices are in Algerian dinars. Euro and dollar displays use store-set rates: 1 EUR = 280 DA and 1 USD = 250 DA. These are display rates, not bank exchange quotes. Delivery fees are added separately and the total is shown before submission. Any additional conditions must be disclosed before purchase confirmation.', 'الأسعار المرجعية بالدينار الجزائري. يعتمد العرض باليورو والدولار على أسعار يحددها المتجر: 1 EUR = 280 DA و1 USD = 250 DA. هذه أسعار للعرض وليست أسعار صرف بنكية. تُضاف رسوم التوصيل منفصلة ويظهر الإجمالي قبل التأكيد. تُوضح أي شروط إضافية قبل تأكيد الشراء.']],
    [['Commande et paiement','Orders and payment','الطلب والدفع'], ['Vérifiez les articles, les tailles et vos coordonnées avant de confirmer. Une commande en DA est enregistrée et réglée à la livraison, au domicile ou au bureau choisi pour l’expédition. L’équipe peut vous contacter pour confirmer les informations et la disponibilité. La page de remerciement confirme l’enregistrement, pas la livraison du colis. Le paiement international par carte via Stripe n’est pas encore activé ; aucune donnée de carte n’est collectée sur le formulaire actuel.', 'Check items, sizes and contact details before submitting. Dinar orders are recorded and paid on delivery, at home or at the office selected for shipment. Staff may contact you to confirm details and availability. The thank-you page confirms registration, not parcel delivery. International card payment through Stripe is not yet active; the current form collects no card details.', 'تحققي من المنتجات والمقاسات وبياناتك قبل التأكيد. يُسجل الطلب بالدينار ويُدفع عند الاستلام في المنزل أو مكتب الشحن المحدد. قد يتواصل الفريق لتأكيد البيانات والتوفر. تؤكد صفحة الشكر تسجيل الطلب وليس تسليم الطرد. الدفع الدولي بالبطاقة عبر Stripe غير مفعّل بعد، ولا يجمع النموذج الحالي بيانات البطاقة.']],
    [['Annulation, livraison et retours','Cancellation, delivery and returns','الإلغاء والتوصيل والإرجاع'], ['Pour modifier ou annuler une commande, contactez-nous rapidement avec sa référence. Après remise au transporteur, nous vous indiquons les possibilités applicables. Les modalités de livraison, les incidents et les demandes de retour sont détaillés dans la page « Livraison & retours ». Aucune disposition de ces conditions ne limite vos droits obligatoires prévus par la loi applicable.', 'To change or cancel an order, contact us promptly with its reference. Once handed to the carrier, we will explain the available options. Delivery, incidents and return requests are described on the “Delivery & returns” page. Nothing in these terms limits your mandatory rights under applicable law.', 'لتعديل الطلب أو إلغائه، تواصلي معنا سريعاً مع مرجعه. بعد تسليمه للناقل، نوضح الخيارات المتاحة. ترد تفاصيل التوصيل والمشكلات وطلبات الإرجاع في صفحة «التوصيل والإرجاع». لا تحد هذه الشروط من الحقوق الإلزامية التي يضمنها القانون المطبق.']],
    [['Réclamations','Complaints','الشكاوى'], ['Pour toute difficulté, écrivez à youcefkhaldi11@hotmail.com ou appelez le 0540787222 en précisant la référence et le problème rencontré. Nous examinons votre demande pour rechercher une solution. Si le différend persiste, les recours disponibles selon la législation applicable restent ouverts.', 'If you experience a problem, email youcefkhaldi11@hotmail.com or call 0540787222 with your order reference and a description of the issue. We will review your request and seek a solution. If a dispute remains unresolved, remedies under applicable law remain available.', 'إذا واجهت مشكلة، راسلينا على youcefkhaldi11@hotmail.com أو اتصلي بالرقم 0540787222 مع مرجع الطلب ووصف المشكلة. ندرس الطلب لإيجاد حل. إذا استمر النزاع، تبقى وسائل الانتصاف المتاحة وفق القانون المطبق قائمة.']]
  ],
  delivery: [
    [['Livraison en Algérie','Delivery in Algeria','التوصيل داخل الجزائر'], ['Les commandes en dinars sont expédiées avec Yalidine dans les zones desservies. Choisissez la wilaya et la commune officielle dans le formulaire, puis une livraison à domicile ou en bureau lorsque cette option est disponible. Pour un retrait, notre équipe organise le bureau d’expédition à partir de votre commande et vous confirme les informations nécessaires.', 'Dinar orders are shipped with Yalidine in served areas. Select your wilaya and official commune in checkout, then home or office delivery where available. For pickup, our team arranges the shipping office using your order details and confirms the necessary information.', 'تُشحن الطلبات بالدينار عبر ياليدين في المناطق التي تغطيها. اختاري الولاية والبلدية الرسمية، ثم التوصيل للمنزل أو للمكتب عندما يكون متاحاً. للاستلام، يرتب فريقنا مكتب الشحن بناءً على بيانات الطلب ويؤكد المعلومات اللازمة.']],
    [['Frais, délais et suivi','Fees, timing and tracking','الرسوم والمدة والتتبع'], ['Les frais suivent la grille par wilaya de la boutique et sont affichés avant confirmation. Une option bureau à 0 DA dans la grille signifie indisponible, pas gratuite. Le délai dépend de la préparation, de la destination et du transporteur ; aucune date fixe n’est garantie sur le site. Après création de l’expédition, un numéro de suivi Yalidine est enregistré avec la commande.', 'Fees follow the store’s wilaya tariff list and are displayed before submission. An office option listed at 0 DA means unavailable, not free. Timing depends on preparation, destination and carrier; the site guarantees no fixed delivery date. A Yalidine tracking number is recorded with the order once shipment is created.', 'تتبع الرسوم قائمة المتجر حسب الولاية وتظهر قبل التأكيد. تعني قيمة 0 DA لخيار المكتب أنه غير متاح وليست توصيلاً مجانياً. تعتمد المدة على التجهيز والوجهة والناقل؛ لا يضمن الموقع تاريخاً ثابتاً. يُسجل رقم تتبع ياليدين مع الطلب بعد إنشاء الشحنة.']],
    [['À la réception et en cas de problème','On receipt and if something is wrong','عند الاستلام أو حدوث مشكلة'], ['Assurez-vous que votre téléphone et votre adresse sont exacts pour faciliter la livraison. Si le colis ou l’article présente un problème, contactez-nous rapidement avec la référence, une description et, si possible, des photos utiles. Conservez l’article et l’emballage le temps de l’examen de votre demande. Une absence de photo ne supprime pas vos droits légaux.', 'Make sure your phone number and address are correct to help delivery. If there is a problem with the parcel or item, contact us promptly with the reference, a description and useful photos if possible. Keep the item and packaging while your request is reviewed. A lack of photos does not remove your legal rights.', 'تأكدي من صحة الهاتف والعنوان لتسهيل التوصيل. إذا وجدت مشكلة في الطرد أو المنتج، تواصلي معنا سريعاً مع المرجع والوصف والصور المفيدة إن أمكن. احتفظي بالمنتج والتغليف أثناء دراسة الطلب. غياب الصور لا يلغي حقوقك القانونية.']],
    [['Demander un retour ou un échange','Request a return or exchange','طلب الإرجاع أو الاستبدال'], ['Contactez la boutique avant d’envoyer un article afin de recevoir les instructions et l’adresse de retour. Précisez le motif et la référence. Les délais, les frais et la solution applicable sont communiqués lors du traitement de la demande, conformément aux droits prévus par la législation applicable. Aucun remboursement automatique ni gratuité générale des retours n’est annoncé sur ce site. En cas d’erreur ou de défaut, nous examinons la solution adaptée sans limiter vos droits obligatoires.', 'Contact the store before sending an item back to receive instructions and a return address. Include the reason and order reference. Timing, fees and the applicable solution are communicated when the request is handled, in accordance with rights under applicable law. This site does not promise automatic refunds or universally free returns. For errors or defects, we review an appropriate solution without limiting mandatory rights.', 'تواصلي مع المتجر قبل إعادة المنتج للحصول على التعليمات وعنوان الإرجاع، مع السبب ومرجع الطلب. تُوضح المدة والرسوم والحل المناسب عند معالجة الطلب وفق الحقوق التي يضمنها القانون المطبق. لا يعد الموقع باسترداد تلقائي أو إرجاع مجاني في جميع الحالات. عند وجود خطأ أو عيب، ندرس الحل المناسب دون الحد من حقوقك الإلزامية.']],
    [['Destinations internationales','International destinations','الوجهات الدولية'], ['Pour une destination hors d’Algérie, contactez-nous avant l’achat. La possibilité d’expédition, le prix du transport, les délais et les éventuels droits ou frais de douane doivent être confirmés avant toute commande internationale. L’affichage en euros ou en dollars ne garantit pas à lui seul une livraison internationale.', 'For destinations outside Algeria, contact us before buying. Shipment availability, transport price, timing and possible customs duties or fees must be confirmed before an international order. Displaying prices in euros or dollars does not itself guarantee international delivery.', 'للوجهات خارج الجزائر، تواصلي معنا قبل الشراء. يجب تأكيد إمكانية الشحن وتكلفته ومدته والرسوم الجمركية المحتملة قبل الطلب الدولي. عرض الأسعار باليورو أو الدولار لا يضمن وحده التوصيل الدولي.']]
  ],
  notices: [
    [['Le site Khadidja Boutique','The Khadidja Boutique website','موقع خديجة بوتيك'], ['khadidja.shop est la boutique en ligne Khadidja Boutique, dédiée aux robes pour femme. Pour une question sur le site, une commande ou vos données, utilisez les coordonnées de contact ci-dessous.', 'khadidja.shop is the Khadidja Boutique online store, dedicated to women’s dresses. For questions about the site, an order or your data, use the contact details below.', 'khadidja.shop هو متجر خديجة بوتيك الإلكتروني المخصص للفساتين النسائية. للاستفسار عن الموقع أو الطلب أو بياناتك، استخدمي بيانات الاتصال أدناه.']],
    [['Contact de la boutique','Store contact','التواصل مع المتجر'], ['E-mail : youcefkhaldi11@hotmail.com. Téléphone : 0540787222. Ces coordonnées permettent de joindre la boutique pour le service client et les demandes liées au site.', 'Email: youcefkhaldi11@hotmail.com. Phone: 0540787222. These details connect you with the store for customer service and website-related requests.', 'البريد الإلكتروني: youcefkhaldi11@hotmail.com. الهاتف: 0540787222. تتيح هذه البيانات التواصل مع المتجر لخدمة العملاء والطلبات المتعلقة بالموقع.']],
    [['Hébergement et réalisation','Hosting and development','الاستضافة والتطوير'], ['Le site est hébergé sur GitHub Pages, un service de GitHub. Les données de la boutique et les accès connectés utilisent Google Firebase. Le relais d’expédition utilise Google Apps Script. Réalisation du site : SITEMAGIQUE, sitemagique.com.', 'The site is hosted on GitHub Pages, a GitHub service. Store data and sign-in use Google Firebase. The shipping relay uses Google Apps Script. Website development: SITEMAGIQUE, sitemagique.com.', 'يُستضاف الموقع على GitHub Pages، وهي خدمة من GitHub. تستخدم بيانات المتجر وتسجيل الدخول Google Firebase، ويستخدم وسيط الشحن Google Apps Script. تطوير الموقع: SITEMAGIQUE، sitemagique.com.']],
    [['Contenus et liens','Content and links','المحتوى والروابط'], ['Les noms, logos, textes et visuels du site sont protégés selon les droits de leurs titulaires. Leur publication sur le site n’autorise pas leur réutilisation commerciale. Les liens vers des sites externes conduisent à des services soumis à leurs propres conditions. Consultez aussi nos conditions d’utilisation et notre politique de confidentialité.', 'Names, logos, text and images are protected by their owners’ rights. Publication on this website does not authorize commercial reuse. External links lead to services governed by their own terms. Please also read our terms of use and privacy policy.', 'تخضع الأسماء والشعارات والنصوص والصور لحقوق أصحابها. نشرها في الموقع لا يجيز إعادة استخدامها تجارياً. تؤدي الروابط الخارجية إلى خدمات تخضع لشروطها الخاصة. راجعي أيضاً شروط الاستخدام وسياسة الخصوصية.']]
  ],
  use: [
    [['Accès au site','Website access','الوصول إلى الموقع'], ['Le site permet de consulter les robes, préparer un panier et transmettre une commande. Certaines fonctions demandent un navigateur compatible et une connexion Internet. Des interruptions peuvent survenir pour maintenance ou incident ; contactez-nous si vous ne pouvez pas finaliser un achat.', 'The site lets you browse dresses, prepare a cart and submit an order. Some features require a compatible browser and internet connection. Maintenance or incidents may cause interruptions; contact us if you cannot complete a purchase.', 'يتيح الموقع تصفح الفساتين وإعداد السلة وإرسال الطلب. تتطلب بعض الوظائف متصفحاً متوافقاً واتصالاً بالإنترنت. قد تحدث انقطاعات بسبب الصيانة أو الأعطال؛ تواصلي معنا إذا تعذر إكمال الشراء.']],
    [['Utilisation responsable','Responsible use','الاستخدام المسؤول'], ['Utilisez vos coordonnées exactes et ne transmettez pas une commande au nom d’un tiers sans son accord. Il est interdit de tenter d’accéder à l’administration sans autorisation, de perturber le service ou d’extraire des données personnelles d’autres personnes. Si vous disposez d’un compte, protégez votre mot de passe et signalez tout accès suspect.', 'Use accurate contact details and do not place an order for another person without their agreement. Unauthorized access to administration, disruption of the service or extraction of other people’s personal data is prohibited. If you have an account, protect your password and report suspicious access.', 'استخدمي بيانات اتصال صحيحة ولا تطلبي باسم شخص آخر دون موافقته. يُمنع الوصول غير المصرح به للإدارة أو تعطيل الخدمة أو استخراج البيانات الشخصية للآخرين. إذا كان لديك حساب، احمي كلمة المرور وأبلغي عن أي وصول مشبوه.']],
    [['Informations et services externes','Information and external services','المعلومات والخدمات الخارجية'], ['Les descriptions et le guide des tailles aident à préparer votre achat ; demandez les mesures du modèle en cas de doute. Les services externes, notamment Firebase, GitHub et Yalidine, appliquent leurs propres conditions. Aucun contenu de cette page ne limite les droits obligatoires du consommateur.', 'Descriptions and the size guide help you prepare your purchase; ask for garment measurements if unsure. External services, including Firebase, GitHub and Yalidine, apply their own terms. Nothing on this page limits mandatory consumer rights.', 'تساعد الأوصاف ودليل المقاسات في التحضير للشراء؛ اطلبي قياسات الموديل عند الشك. تطبق الخدمات الخارجية، ومنها Firebase وGitHub وياليدين، شروطها الخاصة. لا يحد محتوى هذه الصفحة من الحقوق الإلزامية للمستهلك.']],
    [['Évolution des informations','Updates to information','تحديث المعلومات'], ['Les politiques peuvent évoluer avec le fonctionnement de la boutique. La date de mise à jour figure sur chaque page. Une modification substantielle des technologies optionnelles demande un nouveau choix de confidentialité. Les conditions présentées lors de votre achat restent la référence pour cette commande, sous réserve des règles légales applicables.', 'Policies may change as the store evolves. Each page shows its update date. A material change to optional technologies requires a new privacy choice. The terms presented at the time of purchase remain the reference for that order, subject to applicable law.', 'قد تتغير السياسات مع تطور المتجر، ويظهر تاريخ التحديث في كل صفحة. يستلزم التغيير الجوهري في التقنيات الاختيارية اختيار خصوصية جديداً. تبقى الشروط المقدمة عند الشراء مرجعاً لذلك الطلب، مع مراعاة القانون المطبق.']]
  ]
};
function legalFooter() {
  return `<section class="footer-legal" aria-label="${legalText('information')}"><h3>${legalText('information')}</h3><nav>${Object.keys(LEGAL_ROUTES).map(key=>`<a href="${LEGAL_ROUTES[key]}">${legalText(key)}</a>`).join('')}<button type="button" data-cookie-settings>${legalText('settings')}</button></nav></section>`;
}
function legalPage() {
  const key = document.body.dataset.legal;
  const sections = LEGAL_DOCUMENTS[key] || LEGAL_DOCUMENTS.privacy;
  const i = legalLangIndex();
  document.title = legalText(key || 'privacy') + ' | Khadidja Boutique';
  return `<main class="section-wrap legal-page"><header class="legal-heading"><span class="kicker">KHADIDJA BOUTIQUE</span><h1>${legalText(key || 'privacy')}</h1><p>${legalText('intro')}</p><small dir="${i===2?'rtl':'ltr'}">${legalText('updated')}</small></header><div class="legal-layout"><nav class="legal-navigation" aria-label="${legalText('information')}">${Object.keys(LEGAL_ROUTES).map(k=>`<a href="${LEGAL_ROUTES[k]}" ${k===key?'aria-current="page"':''}>${legalText(k)}${svg('arrow')}</a>`).join('')}</nav><article class="legal-content">${sections.map(([title,paragraph],n)=>`<section><span class="legal-number" dir="ltr">${String(n+1).padStart(2,'0')}</span><h2>${escapeHtml(title[i])}</h2><p>${escapeHtml(paragraph[i]).replace(/(youcefkhaldi11@hotmail\.com|khadidja-[a-z0-9-]+|\d+ (?:EUR|USD|DA)|0540787222)/g,'<bdi dir="ltr">$1</bdi>')}</p></section>`).join('')}${key==='cookies'?`<button class="button button-dark" type="button" data-cookie-settings>${legalText('settings')}</button>`:''}<aside class="legal-contact"><h2>${legalText('question')}</h2><a href="${link('/contact/')}">${legalText('contact')}${svg('arrow')}</a><a dir="ltr" href="mailto:youcefkhaldi11@hotmail.com">youcefkhaldi11@hotmail.com</a><a dir="ltr" href="tel:+213540787222">0540787222</a></aside></article></div></main>`;
}

(() => {
  const key = 'khadidja-cookie-consent-v1', version = 1;
  const lifetime = 180 * 24 * 60 * 60 * 1000;
  let memoryChoice = null;
  function readChoice() {
    try {
      const value = JSON.parse(localStorage.getItem(key) || 'null') || memoryChoice;
      if (!value || value.version !== version || !['accepted','rejected','custom'].includes(value.decision) || !Number.isFinite(value.savedAt) || Date.now()-value.savedAt >= lifetime || value.savedAt > Date.now()) return null;
      return value;
    } catch { return memoryChoice; }
  }
  function saveChoice(decision) {
    // There are no optional services. Accepting cannot silently enable future trackers.
    const choice = {version, decision, necessary:true, analytics:false, marketing:false, savedAt:Date.now()};
    memoryChoice = choice;
    try { localStorage.setItem(key, JSON.stringify(choice)); } catch { /* Browsing still works if storage is unavailable. */ }
    document.querySelector('#cookie-banner')?.remove();
    const dialog = document.querySelector('#cookie-preferences');
    if (dialog?.open) dialog.close();
    const status = document.querySelector('#cookie-status');
    if (status) status.textContent = legalText('saved');
    window.dispatchEvent(new CustomEvent('kb:consentchange', {detail:choice}));
  }
  function openPreferences() {
    const dialog = document.querySelector('#cookie-preferences');
    if (dialog && !dialog.open) dialog.showModal();
  }
  window.KBCookies = {getChoice:readChoice, hasConsent:category=>category==='necessary', openPreferences};
  window.setupLegal = function () {
    document.querySelectorAll('[data-cookie-settings]').forEach(button=>button.addEventListener('click',openPreferences));
    let root = document.querySelector('#cookie-consent-root');
    if (!root) { root = document.createElement('div'); root.id='cookie-consent-root'; document.body.append(root); }
    const t = legalText;
    root.innerHTML = `<div id="cookie-status" class="cookie-sr-only" role="status" aria-live="polite"></div>${!readChoice()?`<section id="cookie-banner" class="cookie-banner" role="region" aria-labelledby="cookie-banner-title"><div><h2 id="cookie-banner-title">${t('bannerTitle')}</h2><p>${t('bannerText')} <a href="${link(LEGAL_ROUTES.cookies)}">${t('cookies')}</a></p></div><div class="cookie-actions"><button type="button" data-cookie-decision="accepted">${t('accept')}</button><button type="button" data-cookie-decision="rejected">${t('reject')}</button><button type="button" class="cookie-customize" data-cookie-settings>${t('customize')}</button></div></section>`:''}<dialog id="cookie-preferences" class="cookie-dialog" aria-labelledby="cookie-preferences-title"><div class="cookie-dialog-head"><h2 id="cookie-preferences-title">${t('settingsTitle')}</h2><button type="button" id="cookie-close" aria-label="${t('close')}">${svg('close')}</button></div><p>${t('settingsText')}</p>${[['necessary','necessaryText','active'],['analytics','analyticsText','unused'],['ads','adsText','unused']].map(([title,description,state])=>`<section class="cookie-category"><div><h3>${t(title)}</h3><p>${t(description)}</p></div><span class="cookie-category-state">${t(state)}</span></section>`).join('')}<a class="cookie-policy-link" href="${link(LEGAL_ROUTES.cookies)}">${t('cookies')}</a><div class="cookie-dialog-actions"><button type="button" data-cookie-decision="accepted">${t('accept')}</button><button type="button" data-cookie-decision="rejected">${t('reject')}</button><button type="button" data-cookie-decision="custom">${t('save')}</button></div></dialog>`;
    root.querySelectorAll('[data-cookie-decision]').forEach(button=>button.addEventListener('click',()=>saveChoice(button.dataset.cookieDecision)));
    root.querySelectorAll('[data-cookie-settings]').forEach(button=>button.addEventListener('click',openPreferences));
    root.querySelector('#cookie-close').addEventListener('click',()=>root.querySelector('dialog').close());
  };
})();
