const BASE = location.hostname.endsWith('github.io') ? '/khadidja.github.io' : '';
const link = path => /^(?:https?:|data:|blob:)/.test(path) ? path : BASE + path;
const CART_KEY = 'khadidja-cart-v2';
const LEGACY_CART_KEY = 'khadidja-cart-v1';
const PRODUCTS = [
  {
    id: 'robe-de-soiree-nude-strass',
    name: 'Robe de soirée nude en mousseline à strass',
    short: 'Robe nude à strass',
    description: 'Robe de soirée élégante en mousseline de soie rose nude, ornée de strass. Sa coupe ajustée à la taille s’évase avec grâce sur la longueur. Une étole légère complète la silhouette.',
    details: 'Mousseline de soie, strass, coupe ajustée et évasée.',
    color: 'Nude', swatch: '#eadbd7', sizes: ['46','48','50'], price: 23900,
    images: ['/assets/robe-nude-face.jpg','/assets/robe-nude-detail.jpg','/assets/robe-nude-dos.jpg'],
    url: '/produit/robe-de-soiree-nude-strass/'
  },
  {
    id: 'robe-longue-plissee-bleu-gris-perles',
    name: 'Robe longue plissée bleu gris à perles',
    short: 'Robe plissée bleu gris',
    description: 'Robe longue chic grande taille en tissu maille élastique bleu gris. Son drapé plissé dessine une silhouette fluide et ses perles soulignent le haut de la robe.',
    details: 'Tissu maille élastique, plis et perles décoratives.',
    color: 'Bleu gris', swatch: '#7289a1', sizes: ['46','48','50'], price: 23900,
    images: ['/assets/robe-bleu-face.jpg','/assets/robe-bleu-pose.jpg'],
    url: '/produit/robe-longue-plissee-bleu-gris-perles/'
  }
];
PRODUCTS.forEach(p => { p._source = {name:p.name,short:p.short,description:p.description,details:p.details,color:p.color}; });
const byId = id => PRODUCTS.find(p => p.id === id);
const money = n => formatPrice(n);
const svgPaths = {
  search:'<circle cx="11" cy="11" r="7"/><path d="m16 16 5 5"/>',
  bag:'<path d="M4 8h16l-1 13H5L4 8Z"/><path d="M9 9V6a3 3 0 0 1 6 0v3"/>',
  menu:'<path d="M3 6h18M3 12h18M3 18h18"/>',
  close:'<path d="M5 5l14 14M19 5 5 19"/>',
  arrow:'<path d="M4 12h16m-6-6 6 6-6 6"/>',
  chevron:'<path d="m15 18-6-6 6-6"/>',
  check:'<path d="m4 12 5 5L20 6"/>'
};
const svg = name => `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${svgPaths[name]}</svg>`;
const escapeHtml = value => String(value).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function cartItems() {
  try {
    let raw = JSON.parse(localStorage.getItem(CART_KEY));
    if (!Array.isArray(raw)) {
      const old = JSON.parse(localStorage.getItem(LEGACY_CART_KEY) || '[]');
      raw = Array.isArray(old) && PRODUCTS[0] ? old.map(x => ({id:PRODUCTS[0].id,size:x.size,quantity:x.quantity})) : [];
      localStorage.setItem(CART_KEY, JSON.stringify(raw));
    }
    return raw.filter(x => byId(x.id)?.active!==false && byId(x.id)?.sizes.includes(x.size) && Number.isInteger(x.quantity) && x.quantity > 0);
  } catch { return []; }
}
function saveCart(items) { localStorage.setItem(CART_KEY,JSON.stringify(items)); updateCount(); }
function cartCount() { return cartItems().reduce((sum,item)=>sum+item.quantity,0); }
function cartTotal() { return cartItems().reduce((sum,item)=>sum+byId(item.id).price*item.quantity,0); }
function updateCount() { document.querySelectorAll('[data-cart-count]').forEach(el=>el.textContent=cartCount()); }
function shellHeader() {
  const home = document.body.dataset.page === 'home';
  return `<div class="benefit-bar"><span>KHADIDJA BOUTIQUE</span><span>MODE FEMME · ROBES DE SOIRÉE</span><span>NOUVEAUTÉS EN LIGNE</span></div>
  <header class="site-header ${home?'header-home':'header-inner-page'}"><div class="header-inner">
  <button class="icon-button mobile-menu" id="menu-toggle" aria-label="Ouvrir le menu">${svg('menu')}</button>
  <a class="brand" href="/" aria-label="Khadidja Boutique, accueil"><img src="/assets/${home?'logo-white':'logo-black'}.png" alt=""><span>KHADIDJA</span></a>
  <form class="header-search" id="header-search" role="search"><input name="q" type="search" placeholder="Rechercher une robe…" aria-label="Rechercher"><button aria-label="Rechercher">${svg('search')}</button></form>
  <div class="header-actions"><button class="icon-button search-toggle" id="search-toggle" aria-label="Rechercher">${svg('search')}</button><button class="icon-button bag-link" id="cart-toggle" aria-label="Ouvrir le panier">${svg('bag')}<span class="bag-count" data-cart-count>0</span></button></div></div>
  <nav class="main-nav" id="main-nav" aria-label="Navigation principale"><a href="/">ACCUEIL</a><a href="/robes-de-soiree/">ROBES DE SOIRÉE</a><a href="/nouveautes/">NOUVEAUTÉS</a><a href="/la-maison/">LA BOUTIQUE</a><a href="/guide-tailles/">GUIDE DES TAILLES</a><a href="/aide/">AIDE</a></nav>
  <form class="search-panel" id="search-form" role="search" hidden><label for="search-input">Rechercher une robe</label><div><input id="search-input" name="q" type="search" placeholder="Robe, couleur, détail…"><button type="submit">RECHERCHER</button></div></form></header>
  <div class="drawer-overlay" id="drawer-overlay" hidden></div><aside class="cart-drawer" id="cart-drawer" role="dialog" aria-modal="true" aria-label="Mon panier" aria-hidden="true"><div class="drawer-head"><h2>MON PANIER <span data-cart-count>0</span></h2><button class="icon-button" id="cart-close" aria-label="Fermer le panier">${svg('close')}</button></div><div class="drawer-body" id="drawer-body"></div><div class="drawer-foot"><div class="drawer-total"><span>Sous-total</span><strong id="drawer-total">0 DA</strong></div><a class="button button-dark" href="/commande/">COMMANDER ${svg('arrow')}</a><a class="button button-outline" href="/panier/">ACCÉDER AU PANIER</a></div></aside>`;
}
function shellFooter() { return `<footer class="footer"><div class="footer-grid"><div><a class="footer-brand" href="/"><img src="/assets/logo-white.png" alt=""> KHADIDJA</a><p>La mode des grandes occasions.</p></div><div><h3>ACHETER</h3><a href="/robes-de-soiree/">Robes de soirée</a><a href="/nouveautes/">Nouveautés</a><a href="/panier/">Mon panier</a></div><div><h3>DÉCOUVRIR</h3><a href="/la-maison/">La boutique</a><a href="/guide-tailles/">Guide des tailles</a><a href="/aide/">Aide et commande</a></div><div><h3>INFORMATIONS</h3><p>La disponibilité et la livraison seront confirmées par la boutique.</p><p>L’envoi direct des commandes sera activé prochainement.</p></div></div><div class="footer-bottom">© ${new Date().getFullYear()} KHADIDJA BOUTIQUE</div></footer>`; }
function productCard(p) { return `<article class="product-card"><a href="${p.url}" class="card-image"><img src="${p.images[0]}" alt="${p.name}" loading="lazy"><span class="new-tag">NOUVEAUTÉ</span></a><div class="card-details"><div class="small-label">KHADIDJA BOUTIQUE</div><a class="card-name" href="${p.url}">${p.name}</a><div class="card-price">${money(p.price)}</div><div class="color-label"><span class="color-dot" style="background:${p.swatch};border-color:${p.swatch}"></span> ${p.color}</div></div></article>`; }
function productGrid(list=PRODUCTS.filter(p=>p.active!==false)) { return `<div class="product-grid products-two">${list.map(productCard).join('')}</div>`; }
function homePage() {
  return `<main class="home-v3"><section class="hero-mosaic" aria-label="Sélection mode Khadidja"><div class="mosaic-stack mosaic-left">
    <a href="/robes-de-soiree/" style="--tile:url('/assets/robe-bleu-face.jpg')"><span>STYLES TENDANCE</span></a>
    <a href="/nouveautes/" style="--tile:url('/assets/robe-nude-face.jpg')"><span>NOUVEAUTÉS</span></a>
    <a href="/la-maison/" style="--tile:url('/assets/campaign-black.jpg')"><span>LA BOUTIQUE</span></a></div>
    <div class="mosaic-center"><div class="hero-slide active" data-slide="0"><img src="/assets/campaign-red.jpg" alt="Collection mode rose"><div class="hero-slide-copy"><span>SÉLECTION MODE</span><h1>ROBES DE SOIRÉE</h1><a class="button button-dark" href="/robes-de-soiree/">DÉCOUVRIR LA COLLECTION</a></div></div>
    <div class="hero-slide" data-slide="1"><img src="/assets/robe-bleu-face.jpg" alt="Robe longue bleu gris"><div class="hero-slide-copy"><span>NOUVEAUTÉ</span><h2>BLEU GRIS<br>À PERLES</h2><a class="button button-dark" href="${(PRODUCTS[1]?.url||'/robes-de-soiree/')}">VOIR LA ROBE</a></div></div>
    <button class="slide-arrow slide-prev" data-direction="-1" aria-label="Bannière précédente">${svg('chevron')}</button><button class="slide-arrow slide-next" data-direction="1" aria-label="Bannière suivante">${svg('chevron')}</button><div class="slide-dots"><button class="active" data-go="0" aria-label="Bannière 1"></button><button data-go="1" aria-label="Bannière 2"></button></div></div>
    <div class="mosaic-stack mosaic-right"><a href="${(PRODUCTS[0]?.url||'/robes-de-soiree/')}" style="--tile:url('/assets/robe-nude-detail.jpg')"><span>NUDE À STRASS</span></a><a href="${(PRODUCTS[1]?.url||'/robes-de-soiree/')}" style="--tile:url('/assets/robe-bleu-pose.jpg')"><span>BLEU GRIS À PERLES</span></a><a href="/guide-tailles/" style="--tile:url('/assets/campaign-black.jpg')"><span>VOTRE STYLE</span></a></div></section>
    <div class="home-ribbon"><span>LA MODE DES GRANDES OCCASIONS</span><span>UNE COLLECTION À DÉCOUVRIR</span><span>VOTRE ALLURE, VOTRE MOMENT</span></div>
    <section class="section-wrap home-products"><div class="home-title"><div><span class="kicker">DÉCOUVREZ</span><h2>LES NOUVEAUTÉS</h2></div><a href="/nouveautes/">VOIR TOUT ${svg('arrow')}</a></div>${productGrid()}</section>
    <section class="dual-campaign"><a href="${(PRODUCTS[1]?.url||'/robes-de-soiree/')}"><img src="/assets/robe-bleu-pose.jpg" alt="Robe longue plissée bleu gris"><span>ÉLÉGANCE EN BLEU GRIS <b>DÉCOUVRIR ${svg('arrow')}</b></span></a><a href="${(PRODUCTS[0]?.url||'/robes-de-soiree/')}"><img src="/assets/robe-nude-dos.jpg" alt="Robe de soirée nude vue de dos"><span>DOUCEUR NUDE <b>DÉCOUVRIR ${svg('arrow')}</b></span></a></section>
    <section class="section-wrap home-inspiration"><div class="home-title"><div><span class="kicker">DÉTAILS DE STYLE</span><h2>À CHAQUE ROBE SON ÉCLAT</h2></div></div><div class="inspiration-grid"><a href="${(PRODUCTS[0]?.url||'/robes-de-soiree/')}"><img src="/assets/robe-nude-detail.jpg" alt="Détails de strass"><span>LES STRASS</span></a><a href="${(PRODUCTS[1]?.url||'/robes-de-soiree/')}"><img src="/assets/robe-bleu-face.jpg" alt="Robe plissée et perlée"><span>LES PLIS & LES PERLES</span></a><a href="/la-maison/"><img src="/assets/campaign-black.jpg" alt="Image de campagne mode"><span>L’UNIVERS KHADIDJA</span></a></div><p class="campaign-disclaimer">Les visuels de campagne illustrent l’univers de la boutique. Les photos des robes disponibles figurent sur leurs fiches produit.</p></section></main>`;
}
function pageIntro(label,title,description) { return `<div class="page-intro"><span>${label}</span><h1>${title}</h1><p>${description}</p></div>`; }
function collectionPage() { const q=new URLSearchParams(location.search).get('q')?.trim().toLocaleLowerCase('fr')||''; const list=q?PRODUCTS.filter(p=>p.active!==false).filter(p=>`${p.name} ${p.description} ${p.color}`.toLocaleLowerCase('fr').includes(q)):PRODUCTS.filter(p=>p.active!==false); return `<main class="section-wrap extra-page">${pageIntro('KHADIDJA BOUTIQUE','ROBES DE SOIRÉE',q?`Résultats pour « ${escapeHtml(q)} »`:'Découvrez les robes actuellement disponibles dans la collection.')}<div class="listing-toolbar"><span>${list.length} ARTICLE${list.length>1?'S':''}</span><span>TRIER : NOUVEAUTÉS</span></div>${list.length?`<div class="listing-grid">${list.map(productCard).join('')}</div>`:'<div class="empty-state"><h2>Aucune robe trouvée</h2><a class="button button-dark" href="/robes-de-soiree/">VOIR TOUTES LES ROBES</a></div>'}</main>`; }
function newPage() { const list=PRODUCTS.filter(p=>p.active!==false).slice().reverse();return `<main class="section-wrap extra-page">${pageIntro('JUSTE ARRIVÉES','NOUVEAUTÉS','Les dernières robes de soirée Khadidja Boutique.')}<div class="listing-toolbar"><span>${list.length} ARTICLE${list.length>1?'S':''}</span><span>COLLECTION SOIRÉE</span></div><div class="listing-grid">${list.map(productCard).join('')}</div></main>`; }
function guidePage() { return `<main class="section-wrap extra-page info-page size-guide">
  ${pageIntro('BIEN CHOISIR','GUIDE DES TAILLES','Prenez vos mesures en quelques minutes pour trouver la taille qui vous convient.')}
  <div class="guide-intro"><div><span class="eyebrow">LE BON GESTE</span><h2>Comment prendre vos mesures</h2><p>Utilisez un mètre ruban souple. Mesurez-vous en sous-vêtements, debout et détendue. Gardez le ruban horizontal et près du corps, sans le serrer.</p></div><img src="/assets/robe-bleu-face.jpg" alt="Robe longue bleu gris portée de face"></div>
  <div class="guide-steps"><article><span>01</span><h3>Tour de poitrine</h3><p>Passez le mètre autour de la partie la plus forte de la poitrine, sous les bras et dans le dos.</p></article><article><span>02</span><h3>Tour de taille</h3><p>Mesurez le creux naturel de la taille, généralement au-dessus du nombril. Ne rentrez pas le ventre.</p></article><article><span>03</span><h3>Tour de hanches</h3><p>Entourez la partie la plus large du bassin et des fesses, pieds joints.</p></article></div>
  <section class="guide-chart"><span class="eyebrow">TABLEAU DE CORRESPONDANCE</span><h2>Trouvez votre taille</h2><p>Comparez vos mesures du corps, en centimètres, avec ces repères de confection. Il ne s’agit pas des mesures des robes : la coupe et le tissu peuvent modifier le rendu.</p><div class="guide-table-scroll"><table><thead><tr><th scope="col">Taille</th><th scope="col">Poitrine</th><th scope="col">Tour de taille</th><th scope="col">Hanches</th></tr></thead><tbody><tr><th scope="row">46</th><td>104–108 cm</td><td>86–90 cm</td><td>110–114 cm</td></tr><tr><th scope="row">48</th><td>109–113 cm</td><td>91–95 cm</td><td>115–119 cm</td></tr><tr><th scope="row">50</th><td>114–118 cm</td><td>96–100 cm</td><td>120–124 cm</td></tr></tbody></table></div><p class="guide-note">Ces valeurs sont indicatives. Les mesures exactes de chaque robe ne sont pas encore confirmées par la boutique.</p></section>
  <div class="guide-advice"><div><h2>Entre deux tailles ?</h2><p>Fiez-vous d’abord à la mesure la plus forte. Pour une robe près du corps ou si vous préférez être à l’aise, choisissez la taille supérieure. Le modèle bleu gris est en maille élastique ; la robe nude a une taille ajustée. En cas de doute, demandez-nous les mesures du modèle avant de commander.</p></div><div><h2>Besoin d’un conseil ?</h2><p>Envoyez-nous vos tours de poitrine, taille et hanches, ainsi que le modèle choisi. Nous vous aiderons à sélectionner parmi les tailles 46, 48 et 50.</p><a class="button button-dark" href="/contact/">NOUS CONTACTER ${svg('arrow')}</a></div></div>
  <div class="guide-end"><a href="/robes-de-soiree/">DÉCOUVRIR LES ROBES ${svg('arrow')}</a></div></main>`; }
function aboutPage() { return `<main class="extra-page about-page"><div class="about-hero"><img src="/assets/campaign-black.jpg" alt="Univers mode Khadidja Boutique"><div><span>KHADIDJA BOUTIQUE</span><h1>LA MODE POUR VOS GRANDS MOMENTS</h1><p>Une boutique dédiée aux robes de soirée pour femme.</p></div></div><div class="section-wrap about-story"><div><span>NOTRE UNIVERS</span><h2>Une allure qui vous ressemble.</h2></div><p>Des silhouettes fluides, des couleurs délicates et des détails qui attirent le regard. Découvrez les deux modèles actuellement disponibles dans notre collection.</p></div><section class="section-wrap home-products"><div class="home-title"><div><span class="kicker">LA COLLECTION</span><h2>LES ROBES KHADIDJA</h2></div></div>${productGrid()}</section></main>`; }
function helpPage() { return `<main class="section-wrap extra-page info-page">${pageIntro('INFORMATIONS','AIDE & COMMANDE','Les réponses essentielles pour préparer votre achat.')}<div class="faq-list"><details open><summary>Quels modèles sont disponibles ?</summary><p>Deux robes de soirée sont actuellement proposées : une robe nude à strass et une robe longue bleu gris plissée à perles. Retrouvez leurs photos et détails sur les fiches produit.</p></details><details><summary>Comment choisir une taille ?</summary><p>Les deux modèles sont disponibles en 46, 48 et 50. Consultez le <a href="/guide-tailles/">guide des tailles</a> ; les mesures détaillées restent à confirmer.</p></details><details><summary>Quel est le prix ?</summary><p>Chaque robe est proposée à 23 900 DA, hors éventuels frais de livraison.</p></details><details><summary>Comment fonctionne le panier ?</summary><p>Choisissez une taille sur chaque fiche produit, puis ouvrez l’icône panier en haut de page. Le tiroir vous permet d’accéder au panier ou à la commande.</p></details><details><summary>La commande est-elle envoyée à la boutique ?</summary><p>L’envoi direct n’est pas encore activé. La page de commande prépare un récapitulatif à copier ; aucun message n’est transmis automatiquement.</p></details><details><summary>Quels sont les frais et délais de livraison ?</summary><p>Ils seront confirmés par la boutique avant validation définitive.</p></details></div></main>`; }
function productPage(p) { return `<main class="product-main section-wrap"><div class="breadcrumbs"><a href="/">Accueil</a><span>/</span><a href="/robes-de-soiree/">Robes de soirée</a><span>/</span><span>${p.short}</span></div><div class="product-layout"><div class="gallery"><div class="thumbs">${p.images.map((src,i)=>`<button class="thumb ${i===0?'active':''}" data-image="${i}" aria-label="Voir l’image ${i+1}"><img src="${src}" alt=""></button>`).join('')}</div><div class="main-image"><img id="main-product-image" src="${p.images[0]}" alt="${p.name}"></div></div><div class="product-info"><div class="eyebrow">KHADIDJA BOUTIQUE · ROBES DE SOIRÉE</div><h1>${p.name}</h1><div class="sku">Réf. ${p.sku||p.id}</div><div class="product-price">${money(p.price)}</div><div class="rule"></div><p class="product-description">${p.description}</p><div class="field-title">COULEUR : <strong>${p.color.toUpperCase()}</strong></div><div class="swatch" aria-label="${p.color} sélectionné"><span style="background:${p.swatch}"></span></div><div class="field-title size-title">TAILLE : <strong id="selected-size">Sélectionnez une taille</strong></div><div class="size-options">${p.sizes.map(size=>`<button type="button" data-size="${size}" aria-pressed="false">${size}</button>`).join('')}</div><p class="field-error" id="size-error" role="alert"></p><div class="quantity-wrap"><span class="field-title">QUANTITÉ</span><div class="qty-control"><button type="button" data-qty="minus" aria-label="Diminuer la quantité">−</button><span id="product-qty">1</span><button type="button" data-qty="plus" aria-label="Augmenter la quantité">+</button></div></div><button class="button button-dark add-cart" id="add-cart">AJOUTER AU PANIER ${svg('bag')}</button><p class="product-note">La disponibilité et les modalités de livraison seront confirmées par la boutique.</p><div class="detail-accordion"><details open><summary>DESCRIPTION</summary><p>${p.description}</p></details><details><summary>DÉTAILS</summary><p>${p.details} Tailles : ${p.sizes.join(', ')}.</p></details></div></div></div><section class="more-section"><div class="section-heading"><div><span class="eyebrow">À DÉCOUVRIR</span><h2>Dans la collection</h2></div></div>${productGrid(PRODUCTS.filter(item=>item.id!==p.id&&item.active!==false))}</section></main>`; }
function cartPage() { const items=cartItems(); if(!items.length)return `<main class="simple-page section-wrap"><h1>Mon panier</h1><div class="empty-state">${svg('bag')}<h2>Votre panier est vide</h2><p>Découvrez notre collection de robes de soirée.</p><a class="button button-dark" href="/robes-de-soiree/">VOIR LES ROBES</a></div></main>`; return `<main class="simple-page section-wrap"><h1>Mon panier <span>(${cartCount()})</span></h1><div class="cart-layout"><div class="cart-items">${items.map(item=>{const p=byId(item.id);return `<article class="cart-item"><a href="${p.url}"><img src="${p.images[0]}" alt="${p.name}"></a><div><a class="cart-item-name" href="${p.url}">${p.name}</a><p>Couleur : ${p.color}<br>Taille : ${item.size}</p><strong>${money(p.price*item.quantity)}</strong><div class="cart-item-actions"><div class="qty-control"><button data-cart-change="minus" data-id="${p.id}" data-size="${item.size}" aria-label="Diminuer la quantité">−</button><span>${item.quantity}</span><button data-cart-change="plus" data-id="${p.id}" data-size="${item.size}" aria-label="Augmenter la quantité">+</button></div><button class="remove-link" data-cart-remove="${p.id}" data-size="${item.size}">Supprimer</button></div></div></article>`}).join('')}</div><aside class="summary"><h2>RÉCAPITULATIF</h2><div><span>Articles (${cartCount()})</span><strong>${money(cartTotal())}</strong></div><div><span>Livraison</span><strong>À confirmer</strong></div><hr><div class="total"><span>Sous-total</span><strong>${money(cartTotal())}</strong></div><a class="button button-dark" href="/commande/">PASSER COMMANDE ${svg('arrow')}</a><a class="continue-link" href="/robes-de-soiree/">Continuer mes achats</a></aside></div></main>`; }
function checkoutPage() { const items=cartItems(); if(!items.length)return `<main class="simple-page section-wrap"><h1>Ma commande</h1><div class="empty-state"><h2>Votre panier est vide</h2><a class="button button-dark" href="/robes-de-soiree/">VOIR LES ROBES</a></div></main>`; return `<main class="simple-page section-wrap"><div class="breadcrumbs"><a href="/panier/">Panier</a><span>/</span>Commande</div><h1>Finaliser ma commande</h1><div class="cart-layout"><form id="checkout-form" class="checkout-form"><h2>VOS COORDONNÉES</h2><p>Renseignez vos informations pour préparer votre demande.</p><div class="form-grid"><label>Nom et prénom *<input name="name" autocomplete="name" required maxlength="100"></label><label>Téléphone *<input name="phone" type="tel" autocomplete="tel" required maxlength="30"></label><label>Wilaya *<input name="wilaya" autocomplete="address-level1" required maxlength="80"></label><label>Commune *<input name="commune" autocomplete="address-level2" required maxlength="80"></label></div><label>Adresse de livraison *<input name="address" autocomplete="street-address" required maxlength="200"></label><label>Précisions pour la commande<textarea name="notes" rows="4" maxlength="500" placeholder="Informations utiles pour la livraison…"></textarea></label><p class="checkout-warning">Les frais de livraison doivent être confirmés avant validation définitive. Aucun message n’est envoyé automatiquement pour l’instant.</p><button class="button button-dark" type="submit">PRÉPARER MA DEMANDE ${svg('arrow')}</button><div id="checkout-result" class="checkout-result" hidden></div></form><aside class="summary"><h2>VOTRE COMMANDE</h2>${items.map(item=>{const p=byId(item.id);return `<div class="checkout-item"><img src="${p.images[0]}" alt=""><p>${p.name}<small>${p.color} · Taille ${item.size} · Qté ${item.quantity}</small></p></div>`}).join('')}<hr><div><span>Articles</span><strong>${cartCount()}</strong></div><div><span>Sous-total</span><strong>${money(cartTotal())}</strong></div><div><span>Livraison</span><strong>À confirmer</strong></div></aside></div></main>`; }
function renderDrawer() { const items=cartItems(); document.querySelector('#drawer-body').innerHTML=items.length?items.map(item=>{const p=byId(item.id);return `<article class="drawer-item"><img src="${link(p.images[0])}" alt="${p.name}"><div><a href="${link(p.url)}">${p.name}</a><p>${p.color} · Taille ${item.size} · Qté ${item.quantity}</p><strong>${money(p.price*item.quantity)}</strong></div></article>`}).join(''):`<div class="drawer-empty">${svg('bag')}<h3>VOTRE PANIER EST VIDE</h3><p>Découvrez nos robes de soirée.</p><a href="${link('/robes-de-soiree/')}">VOIR LA COLLECTION</a></div>`;document.querySelector('#drawer-total').textContent=money(cartTotal());document.querySelector('.drawer-foot').style.display=items.length?'block':'none'; }
function setupShell() { const drawer=document.querySelector('#cart-drawer'), overlay=document.querySelector('#drawer-overlay'); const close=()=>{drawer.classList.remove('open');drawer.setAttribute('aria-hidden','true');overlay.hidden=true;document.body.classList.remove('drawer-open')};document.querySelector('#cart-toggle').addEventListener('click',()=>{renderDrawer();drawer.classList.add('open');drawer.setAttribute('aria-hidden','false');overlay.hidden=false;document.body.classList.add('drawer-open');document.querySelector('#cart-close').focus()});document.querySelector('#cart-close').addEventListener('click',close);overlay.addEventListener('click',close);document.addEventListener('keydown',e=>{if(e.key==='Escape')close()});document.querySelector('#menu-toggle').addEventListener('click',()=>document.querySelector('#main-nav').classList.toggle('open'));document.querySelector('#search-toggle').addEventListener('click',()=>{const panel=document.querySelector('#search-form');panel.hidden=!panel.hidden;if(!panel.hidden)panel.querySelector('input').focus()});document.querySelectorAll('#header-search,#search-form').forEach(form=>form.addEventListener('submit',e=>{e.preventDefault();const q=form.querySelector('input').value.trim();location.href=link('/robes-de-soiree/')+(q?`?q=${encodeURIComponent(q)}`:'')})); }
function setupHero() { const slides=[...document.querySelectorAll('.hero-slide')],dots=[...document.querySelectorAll('[data-go]')];if(!slides.length)return;let current=0;const show=i=>{current=(i+slides.length)%slides.length;slides.forEach((el,n)=>{el.classList.toggle('active',n===current);el.setAttribute('aria-hidden',String(n!==current))});dots.forEach((el,n)=>el.classList.toggle('active',n===current))};document.querySelectorAll('[data-direction]').forEach(button=>button.addEventListener('click',()=>show(current+Number(button.dataset.direction))));dots.forEach(button=>button.addEventListener('click',()=>show(Number(button.dataset.go))));show(0); }
function setupProduct(p) { let selected=null,quantity=1;document.querySelectorAll('[data-image]').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('.thumb').forEach(el=>el.classList.remove('active'));button.classList.add('active');const i=Number(button.dataset.image);document.querySelector('#main-product-image').src=link(p.images[i])}));document.querySelectorAll('[data-size]').forEach(button=>button.addEventListener('click',()=>{selected=button.dataset.size;document.querySelectorAll('[data-size]').forEach(el=>el.setAttribute('aria-pressed',String(el===button)));document.querySelector('#selected-size').textContent=selected;document.querySelector('#size-error').textContent=''}));document.querySelectorAll('[data-qty]').forEach(button=>button.addEventListener('click',()=>{quantity=Math.max(1,Math.min(99,quantity+(button.dataset.qty==='plus'?1:-1)));document.querySelector('#product-qty').textContent=quantity}));document.querySelector('#add-cart').addEventListener('click',()=>{if(!selected){document.querySelector('#size-error').textContent='Veuillez choisir une taille.';return}const items=cartItems(),existing=items.find(x=>x.id===p.id&&x.size===selected);if(existing)existing.quantity=Math.min(99,existing.quantity+quantity);else items.push({id:p.id,size:selected,quantity});saveCart(items);location.href=link('/panier/')}); }
function setupCart() { document.querySelectorAll('[data-cart-change]').forEach(button=>button.addEventListener('click',()=>{const items=cartItems(),item=items.find(x=>x.id===button.dataset.id&&x.size===button.dataset.size);if(item)item.quantity+=button.dataset.cartChange==='plus'?1:-1;saveCart(items.filter(x=>x.quantity>0));render()}));document.querySelectorAll('[data-cart-remove]').forEach(button=>button.addEventListener('click',()=>{saveCart(cartItems().filter(x=>!(x.id===button.dataset.cartRemove&&x.size===button.dataset.size)));render()})); }
function setupCheckout() { const form=document.querySelector('#checkout-form');if(!form)return;form.addEventListener('submit',e=>{e.preventDefault();const data=new FormData(form),items=cartItems();const values=Object.fromEntries(['name','phone','wilaya','commune','address','notes'].map(k=>[k,String(data.get(k)||'').trim()]));const lines=['Bonjour Khadidja Boutique, je souhaite commander :',...items.map(item=>{const p=byId(item.id);return `• ${p.name} — ${p.color}, taille ${item.size}, quantité ${item.quantity}`}),`Sous-total : ${money(cartTotal())}`,'Livraison : à confirmer',`Nom : ${values.name}`,`Téléphone : ${values.phone}`,`Wilaya : ${values.wilaya}`,`Commune : ${values.commune}`,`Adresse : ${values.address}`,`Précisions : ${values.notes||'Aucune'}`];const message=lines.join('\n'),result=document.querySelector('#checkout-result');result.hidden=false;result.innerHTML=`<strong>Votre demande est prête.</strong><p>Copiez ce récapitulatif. Aucun message n’a été envoyé à la boutique.</p><textarea readonly rows="12" id="order-message">${escapeHtml(message)}</textarea><button type="button" class="button button-outline" id="copy-order">COPIER LA DEMANDE</button>`;document.querySelector('#copy-order').addEventListener('click',async()=>{await navigator.clipboard.writeText(message);document.querySelector('#copy-order').textContent='DEMANDE COPIÉE'});result.scrollIntoView({behavior:'smooth',block:'center'})}); }
function render() {
  if(typeof prepareLocale==='function')prepareLocale();
  const page=document.body.dataset.page;
  const productId=document.body.dataset.productId || new URLSearchParams(location.search).get('id');
  const p=byId(productId);
  const missingProduct=`<main class="simple-page section-wrap"><h1>${window.KB_CATALOG_READY?'Robe indisponible':'Chargement de la robe…'}</h1><a class="button button-dark" href="/robes-de-soiree/">VOIR LES ROBES</a></main>`;
  let body=page==='product'?(p&&p.active!==false?productPage(p):missingProduct):page==='cart'?cartPage():page==='checkout'?checkoutPage():page==='collection'?collectionPage():page==='new'?newPage():page==='guide'?guidePage():page==='about'?aboutPage():page==='help'?helpPage():page==='profile'?profilePage():page==='contact'?contactPage():homePage();
  document.querySelector('#app').innerHTML=(shellHeader()+body+shellFooter()).replace(/(href|src)="\//g,`$1="${BASE}/`).replace(/url\('\/assets/g,`url('${BASE}/assets`);
  updateCount();setupShell();if(page==='home')setupHero();if(page==='product'&&p&&p.active!==false)setupProduct(p);if(page==='cart')setupCart();if(page==='checkout')setupCheckout();if(typeof setupPro==='function')setupPro();
}
document.addEventListener('DOMContentLoaded',()=>{
  if (window.KB_CATALOG_READY === false) return;
  render();
});
