function header() {
  return `<div class="benefit-bar"><span>MODE FEMME</span><span>ROBES DE SOIRÉE</span><span>TAILLES 46 · 48 · 50</span></div>
  <header class="site-header"><div class="header-inner"><button class="icon-button mobile-menu" id="menu-toggle" aria-label="Ouvrir le menu">${svg('menu')}</button>
  <a class="brand" href="/" aria-label="Khadidja Boutique, accueil"><img src="/assets/logo-white.png" alt=""><span>KHADIDJA</span></a>
  <form class="header-search" id="header-search" role="search"><input type="search" placeholder="Rechercher une robe, une taille…" aria-label="Rechercher"><button aria-label="Rechercher">${svg('search')}</button></form>
  <div class="header-actions"><button class="icon-button search-toggle" id="search-toggle" aria-label="Rechercher">${svg('search')}</button><button class="icon-button bag-link" id="cart-toggle" aria-label="Ouvrir le panier">${svg('bag')}<span class="bag-count" data-cart-count>0</span></button></div></div>
  <nav class="main-nav" id="main-nav" aria-label="Navigation principale"><a href="/">ACCUEIL</a><a href="/robes-de-soiree/">ROBES DE SOIRÉE</a><a href="/nouveautes/">NOUVEAUTÉS</a><a href="/guide-tailles/">GUIDE DES TAILLES</a><a href="/la-maison/">LA BOUTIQUE</a><a href="/aide/">AIDE</a></nav>
  <form class="search-panel" id="search-form" role="search" hidden><label for="search-input">Rechercher une robe</label><div><input id="search-input" type="search" placeholder="Robe de soirée, strass, nude…"><button type="submit">RECHERCHER</button></div></form></header>
  <div class="drawer-overlay" id="drawer-overlay" hidden></div><aside class="cart-drawer" id="cart-drawer" role="dialog" aria-modal="true" aria-label="Mon panier" aria-hidden="true"><div class="drawer-head"><h2>MON PANIER <span data-cart-count>0</span></h2><button class="icon-button" id="cart-close" aria-label="Fermer le panier">${svg('close')}</button></div><div class="drawer-body" id="drawer-body"></div><div class="drawer-foot"><div class="drawer-total"><span>Sous-total</span><strong id="drawer-total">0 DA</strong></div><a class="button button-dark" href="/commande/">COMMANDER ${svg('arrow')}</a><a class="button button-outline" href="/panier/">ACCÉDER AU PANIER</a></div></aside>`;
}

function footer() {
  return `<footer class="footer" id="maison"><div class="footer-grid"><div><a class="footer-brand" href="/"><img src="/assets/logo-white.png" alt=""> KHADIDJA</a><p>La mode des grandes occasions.</p></div><div><h3>ACHETER</h3><a href="/robes-de-soiree/">Robes de soirée</a><a href="/nouveautes/">Nouveautés</a><a href="/panier/">Mon panier</a></div><div><h3>DÉCOUVRIR</h3><a href="/la-maison/">La boutique</a><a href="/guide-tailles/">Guide des tailles</a><a href="/aide/">Aide et commande</a></div><div><h3>INFORMATIONS</h3><p>Prix de la robe : 23 900 DA.</p><p>Livraison à confirmer. L’envoi des commandes sera activé prochainement.</p></div></div><div class="footer-bottom">© ${new Date().getFullYear()} KHADIDJA BOUTIQUE</div></footer>`;
}

function home() {
  return `<main class="home-v2"><section class="campaign-hero"><img src="/assets/campaign-red.jpg" alt="Campagne mode de soirée rose et fuchsia"><div class="campaign-copy"><span>LA COLLECTION SOIRÉE</span><h1>Une soirée.<br>Votre moment.</h1><p>Des robes qui attirent tous les regards.</p><a class="button button-white" href="/robes-de-soiree/">DÉCOUVRIR LES ROBES ${svg('arrow')}</a></div></section>
  <div class="home-quick-links"><a href="/robes-de-soiree/"><img src="/assets/robe-nude-face.jpg" alt=""><span>ROBES DE SOIRÉE</span></a><a href="/nouveautes/"><img src="/assets/robe-nude-detail.jpg" alt=""><span>NOUVEAUTÉS</span></a><a href="/guide-tailles/"><img src="/assets/campaign-black.jpg" alt=""><span>GUIDE DES TAILLES</span></a></div>
  <section class="home-shop section-wrap"><div class="home-title"><div><span class="kicker">SHOP THE LOOK</span><h2>À LA UNE</h2></div><a href="/robes-de-soiree/">VOIR TOUT ${svg('arrow')}</a></div><div class="feature-grid"><a class="feature-main" href="${PRODUCT.url}"><img src="${PRODUCT.images[0]}" alt="Robe de soirée nude à strass"><span>LA ROBE DE SOIRÉE <b>23 900 DA</b></span></a><div class="feature-side"><a href="${PRODUCT.url}"><img src="${PRODUCT.images[1]}" alt="Détail des strass de la robe"><span>LE DÉTAIL QUI CHANGE TOUT ${svg('arrow')}</span></a><a href="${PRODUCT.url}"><img src="${PRODUCT.images[2]}" alt="Vue de dos de la robe"><span>UNE ALLURE SOUS TOUS LES ANGLES ${svg('arrow')}</span></a></div></div></section>
  <section class="black-promo"><div><span>KHADIDJA BOUTIQUE</span><h2>LE SOIR VOUS APPARTIENT</h2><p>Une sélection de robes pour marquer les grandes occasions.</p><a href="/nouveautes/" class="button button-white">DÉCOUVRIR ${svg('arrow')}</a></div><img src="/assets/campaign-black.jpg" alt="Campagne mode en robe noire à sequins"></section>
  <section class="home-products section-wrap"><div class="home-title"><div><span class="kicker">NOUVEAUTÉ</span><h2>LE COUP DE CŒUR DU MOMENT</h2></div><a href="/nouveautes/">VOIR LES NOUVEAUTÉS ${svg('arrow')}</a></div><div class="product-showcase"><div>${card()}</div><div class="product-showcase-copy"><span class="kicker">ROBES DE SOIRÉE</span><h3>Robe nude<br>à strass</h3><p>Une coupe ajustée puis évasée, une mousseline légère et des détails scintillants. Disponible en tailles 46, 48 et 50.</p><strong>23 900 DA</strong><a class="button button-dark" href="${PRODUCT.url}">VOIR LE PRODUIT ${svg('arrow')}</a></div></div></section>
  <section class="home-looks section-wrap"><div class="home-title"><div><span class="kicker">INSPIRATION</span><h2>L’ART DE BRILLER</h2></div></div><div class="looks-grid"><a href="/robes-de-soiree/" class="look-big"><img src="/assets/campaign-black.jpg" alt="Inspiration mode robe noire"><span>DES ALLURES QUI MARQUENT ${svg('arrow')}</span></a><a href="${PRODUCT.url}" class="look-small"><img src="${PRODUCT.images[0]}" alt="Robe nude Khadidja Boutique"><span>UNE ROBE, UN MOMENT INOUBLIABLE ${svg('arrow')}</span></a></div><p class="campaign-disclaimer">Les images de campagne illustrent l’univers de la boutique. La robe disponible est présentée avec ses photos sur sa fiche produit.</p></section>
  <section class="home-help"><div><b>01</b><h3>CHOISISSEZ VOTRE TAILLE</h3><p>La robe est proposée en 46, 48 et 50.</p><a href="/guide-tailles/">GUIDE DES TAILLES</a></div><div><b>02</b><h3>AJOUTEZ AU PANIER</h3><p>Retrouvez vos articles dans le tiroir panier à tout moment.</p><a href="/robes-de-soiree/">DÉCOUVRIR LA ROBE</a></div><div><b>03</b><h3>PRÉPAREZ VOTRE COMMANDE</h3><p>L’envoi à la boutique sera disponible prochainement.</p><a href="/aide/">EN SAVOIR PLUS</a></div></section></main>`;
}

function pageIntro(eyebrow,title,description) { return `<div class="page-intro"><span>${eyebrow}</span><h1>${title}</h1><p>${description}</p></div>`; }
function collectionPage() { return `<main class="section-wrap extra-page">${pageIntro('KHADIDJA BOUTIQUE','ROBES DE SOIRÉE','Découvrez la robe actuellement disponible dans la collection.')}
  <div class="listing-toolbar"><span>1 ARTICLE</span><span>TAILLES 46 · 48 · 50</span></div><div class="listing-grid">${card()}</div><section class="listing-banner"><img src="/assets/campaign-red.jpg" alt="Campagne mode rose"><div><span>COLLECTION SOIRÉE</span><h2>PRÊTE À BRILLER ?</h2><a class="button button-white" href="${PRODUCT.url}">VOIR LA ROBE ${svg('arrow')}</a></div></section></main>`; }
function newPage() { return `<main class="section-wrap extra-page">${pageIntro('JUSTE ARRIVÉE','NOUVEAUTÉS','La dernière pièce ajoutée à Khadidja Boutique.')}
  <div class="listing-toolbar"><span>1 NOUVEAUTÉ</span><span>ROBES POUR FEMME</span></div><div class="listing-grid">${card()}</div><div class="info-strip">De nouveaux modèles seront ajoutés ici dès qu’ils seront disponibles.</div></main>`; }
function guidePage() { return `<main class="section-wrap extra-page info-page">${pageIntro('BIEN CHOISIR','GUIDE DES TAILLES','La robe est disponible en tailles 46, 48 et 50.')}
  <div class="info-columns"><div><h2>CHOISIR SA TAILLE</h2><p>Référez-vous à la taille que vous portez habituellement pour une robe ajustée. Les mesures exactes de ce modèle seront ajoutées après confirmation auprès de la boutique.</p><div class="size-table"><div><b>TAILLE DISPONIBLE</b><b>46</b><b>48</b><b>50</b></div><div><span>Couleur</span><span>Nude</span><span>Nude</span><span>Nude</span></div></div><p>Si vous hésitez entre deux tailles, demandez confirmation avant de valider votre achat.</p><a class="button button-dark" href="${PRODUCT.url}">VOIR LA ROBE ${svg('arrow')}</a></div><img src="${PRODUCT.images[1]}" alt="Détail de la robe nude"></div></main>`; }
function aboutPage() { return `<main class="extra-page about-page"><div class="about-hero"><img src="/assets/campaign-black.jpg" alt="Inspiration mode de soirée"><div><span>KHADIDJA BOUTIQUE</span><h1>LA MODE POUR VOS GRANDS MOMENTS</h1><p>Une boutique dédiée aux robes pour femme et aux silhouettes de soirée.</p></div></div><div class="section-wrap about-story"><div><span>NOTRE UNIVERS</span><h2>Une allure qui vous ressemble.</h2></div><p>Chez Khadidja Boutique, la sélection est pensée autour des occasions spéciales. Retrouvez actuellement notre robe de soirée nude à strass, disponible en tailles 46, 48 et 50.</p></div><div class="section-wrap about-cta"><img src="${PRODUCT.images[0]}" alt="Robe de soirée nude"><div><h2>DÉCOUVREZ LA ROBE</h2><p>Mousseline légère, taille marquée et détails scintillants.</p><a href="${PRODUCT.url}" class="button button-dark">VOIR LE PRODUIT ${svg('arrow')}</a></div></div></main>`; }
function helpPage() { return `<main class="section-wrap extra-page info-page">${pageIntro('INFORMATIONS','AIDE & COMMANDE','Les réponses essentielles pour préparer votre achat.')}
  <div class="faq-list"><details open><summary>Comment choisir une taille ?</summary><p>La robe est disponible en 46, 48 et 50. Consultez le <a href="/guide-tailles/">guide des tailles</a> et faites confirmer votre choix si nécessaire.</p></details><details><summary>Quel est le prix ?</summary><p>La robe de soirée nude à strass est proposée à 23 900 DA, hors éventuels frais de livraison.</p></details><details><summary>Comment fonctionne le panier ?</summary><p>Choisissez une taille sur la fiche produit, ajoutez la robe au panier et ouvrez le tiroir panier grâce à l’icône en haut de la page. Vous pourrez y modifier votre commande.</p></details><details><summary>La commande est-elle envoyée à la boutique ?</summary><p>L’envoi direct n’est pas encore activé. La page de commande prépare un récapitulatif que vous pouvez copier. Aucun message n’est transmis automatiquement.</p></details><details><summary>Quels sont les frais et délais de livraison ?</summary><p>Ils seront confirmés par la boutique avant validation définitive.</p></details></div></main>`; }

function setupExtras() {
  const drawer=$('#cart-drawer'), overlay=$('#drawer-overlay');
  const render=()=>{const items=getCart();$('#drawer-body').innerHTML=items.length?items.map(item=>`<article class="drawer-item"><img src="${siteUrl(PRODUCT.images[0])}" alt="${PRODUCT.name}"><div><a href="${siteUrl(PRODUCT.url)}">${PRODUCT.name}</a><p>Nude · Taille ${item.size} · Qté ${item.quantity}</p><strong>${money(CONFIG.priceDa*item.quantity)}</strong></div></article>`).join(''):`<div class="drawer-empty">${svg('bag')}<h3>VOTRE PANIER EST VIDE</h3><p>Découvrez notre robe de soirée.</p><a href="${siteUrl('/robes-de-soiree/')}">VOIR LA COLLECTION</a></div>`;$('#drawer-total').textContent=money(items.reduce((sum,item)=>sum+item.quantity*CONFIG.priceDa,0));$('.drawer-foot').style.display=items.length?'block':'none';};
  const close=()=>{drawer.classList.remove('open');drawer.setAttribute('aria-hidden','true');overlay.hidden=true;document.body.classList.remove('drawer-open');};
  $('#cart-toggle').addEventListener('click',()=>{render();drawer.classList.add('open');drawer.setAttribute('aria-hidden','false');overlay.hidden=false;document.body.classList.add('drawer-open');$('#cart-close').focus();});
  $('#cart-close').addEventListener('click',close);overlay.addEventListener('click',close);
  document.addEventListener('keydown',e=>{if(e.key==='Escape'&&drawer.classList.contains('open'))close();},{once:false});
  $('#header-search').addEventListener('submit',e=>{e.preventDefault();location.href=siteUrl('/robes-de-soiree/');});
}
